/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppType } from './AppType';
import {
    AppTypeFromJSON,
    AppTypeFromJSONTyped,
    AppTypeToJSON,
} from './AppType';
import type { PrincipalType } from './PrincipalType';
import {
    PrincipalTypeFromJSON,
    PrincipalTypeFromJSONTyped,
    PrincipalTypeToJSON,
} from './PrincipalType';

/**
 * 
 * @export
 * @interface AppRegistration
 */
export interface AppRegistration {
    /**
     * 
     * @type {string}
     * @memberof AppRegistration
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AppRegistration
     */
    clientId: string;
    /**
     * 
     * @type {string}
     * @memberof AppRegistration
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AppRegistration
     */
    description: string;
    /**
     * 
     * @type {PrincipalType}
     * @memberof AppRegistration
     */
    principalType: PrincipalType;
    /**
     * 
     * @type {AppType}
     * @memberof AppRegistration
     */
    type: AppType;
    /**
     * 
     * @type {Date}
     * @memberof AppRegistration
     */
    secretExpiresAt?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof AppRegistration
     */
    isArchived: boolean;
    /**
     * 
     * @type {Date}
     * @memberof AppRegistration
     */
    updatedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof AppRegistration
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof AppRegistration
     */
    createdBy: string;
}

/**
 * Check if a given object implements the AppRegistration interface.
 */
export function instanceOfAppRegistration(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "clientId" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "principalType" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "isArchived" in value;
    isInstance = isInstance && "updatedAt" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "createdBy" in value;

    return isInstance;
}

export function AppRegistrationFromJSON(json: any): AppRegistration {
    return AppRegistrationFromJSONTyped(json, false);
}

export function AppRegistrationFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppRegistration {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'clientId': json['clientId'],
        'name': json['name'],
        'description': json['description'],
        'principalType': PrincipalTypeFromJSON(json['principalType']),
        'type': AppTypeFromJSON(json['type']),
        'secretExpiresAt': !exists(json, 'secretExpiresAt') ? undefined : (json['secretExpiresAt'] === null ? null : new Date(json['secretExpiresAt'])),
        'isArchived': json['isArchived'],
        'updatedAt': (new Date(json['updatedAt'])),
        'createdAt': (new Date(json['createdAt'])),
        'createdBy': json['createdBy'],
    };
}

export function AppRegistrationToJSON(value?: AppRegistration | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'clientId': value.clientId,
        'name': value.name,
        'description': value.description,
        'principalType': PrincipalTypeToJSON(value.principalType),
        'type': AppTypeToJSON(value.type),
        'secretExpiresAt': value.secretExpiresAt === undefined ? undefined : (value.secretExpiresAt === null ? null : value.secretExpiresAt.toISOString()),
        'isArchived': value.isArchived,
        'updatedAt': (value.updatedAt.toISOString()),
        'createdAt': (value.createdAt.toISOString()),
        'createdBy': value.createdBy,
    };
}

