/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ArtifactType } from './ArtifactType';
import {
    ArtifactTypeFromJSON,
    ArtifactTypeFromJSONTyped,
    ArtifactTypeToJSON,
} from './ArtifactType';

/**
 * A secondary file or resource associated with a dataset
 * @export
 * @interface Artifact
 */
export interface Artifact {
    /**
     * 
     * @type {ArtifactType}
     * @memberof Artifact
     */
    type: ArtifactType;
    /**
     * 
     * @type {string}
     * @memberof Artifact
     */
    relativePath: string;
}

/**
 * Check if a given object implements the Artifact interface.
 */
export function instanceOfArtifact(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "relativePath" in value;

    return isInstance;
}

export function ArtifactFromJSON(json: any): Artifact {
    return ArtifactFromJSONTyped(json, false);
}

export function ArtifactFromJSONTyped(json: any, ignoreDiscriminator: boolean): Artifact {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': ArtifactTypeFromJSON(json['type']),
        'relativePath': json['relativePath'],
    };
}

export function ArtifactToJSON(value?: Artifact | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': ArtifactTypeToJSON(value.type),
        'relativePath': value.relativePath,
    };
}

