/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum BillingMethod {
    BudgetNumber = 'BUDGET_NUMBER',
    PurchaseOrder = 'PURCHASE_ORDER',
    Credit = 'CREDIT'
}


export function instanceOfBillingMethod(value: any): boolean {
    for (const key in BillingMethod) {
        if (Object.prototype.hasOwnProperty.call(BillingMethod, key)) {
            if (BillingMethod[key as keyof typeof BillingMethod] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BillingMethodFromJSON(json: any): BillingMethod {
    return BillingMethodFromJSONTyped(json, false);
}

export function BillingMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): BillingMethod {
    return json as BillingMethod;
}

export function BillingMethodToJSON(value?: BillingMethod | null): any {
    return value as any;
}

export function BillingMethodToJSONTyped(value: any, ignoreDiscriminator: boolean): BillingMethod {
    return value as BillingMethod;
}

