/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClassificationInput
 */
export interface ClassificationInput {
    /**
     * 
     * @type {string}
     * @memberof ClassificationInput
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ClassificationInput
     */
    description: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ClassificationInput
     */
    requirementIds: Array<string>;
}

/**
 * Check if a given object implements the ClassificationInput interface.
 */
export function instanceOfClassificationInput(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "requirementIds" in value;

    return isInstance;
}

export function ClassificationInputFromJSON(json: any): ClassificationInput {
    return ClassificationInputFromJSONTyped(json, false);
}

export function ClassificationInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClassificationInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
        'requirementIds': json['requirementIds'],
    };
}

export function ClassificationInputToJSON(value?: ClassificationInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'requirementIds': value.requirementIds,
    };
}

