/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProjectRole } from './ProjectRole';
import {
    ProjectRoleFromJSON,
    ProjectRoleFromJSONTyped,
    ProjectRoleToJSON,
} from './ProjectRole';

/**
 * 
 * @export
 * @interface CreateProjectAccessRequest
 */
export interface CreateProjectAccessRequest {
    /**
     * 
     * @type {ProjectRole}
     * @memberof CreateProjectAccessRequest
     */
    role: ProjectRole;
    /**
     * 
     * @type {string}
     * @memberof CreateProjectAccessRequest
     */
    message: string;
}

/**
 * Check if a given object implements the CreateProjectAccessRequest interface.
 */
export function instanceOfCreateProjectAccessRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "role" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function CreateProjectAccessRequestFromJSON(json: any): CreateProjectAccessRequest {
    return CreateProjectAccessRequestFromJSONTyped(json, false);
}

export function CreateProjectAccessRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProjectAccessRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'role': ProjectRoleFromJSON(json['role']),
        'message': json['message'],
    };
}

export function CreateProjectAccessRequestToJSON(value?: CreateProjectAccessRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'role': ProjectRoleToJSON(value.role),
        'message': value.message,
    };
}

