/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateResponse
 */
export interface CreateResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CreateResponse
     */
    message: string;
}

/**
 * Check if a given object implements the CreateResponse interface.
 */
export function instanceOfCreateResponse(value: object): value is CreateResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function CreateResponseFromJSON(json: any): CreateResponse {
    return CreateResponseFromJSONTyped(json, false);
}

export function CreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'message': json['message'],
    };
}

export function CreateResponseToJSON(json: any): CreateResponse {
    return CreateResponseToJSONTyped(json, false);
}

export function CreateResponseToJSONTyped(value?: CreateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'message': value['message'],
    };
}

