/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomPipelineSettings
 */
export interface CustomPipelineSettings {
    /**
     * 
     * @type {string}
     * @memberof CustomPipelineSettings
     */
    repository: string;
    /**
     * 
     * @type {string}
     * @memberof CustomPipelineSettings
     */
    branch: string;
    /**
     * 
     * @type {string}
     * @memberof CustomPipelineSettings
     */
    folder: string;
    /**
     * 
     * @type {Date}
     * @memberof CustomPipelineSettings
     */
    lastSync: Date;
    /**
     * 
     * @type {string}
     * @memberof CustomPipelineSettings
     */
    syncStatus: string;
    /**
     * 
     * @type {string}
     * @memberof CustomPipelineSettings
     */
    commitHash: string;
}

/**
 * Check if a given object implements the CustomPipelineSettings interface.
 */
export function instanceOfCustomPipelineSettings(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "repository" in value;
    isInstance = isInstance && "branch" in value;
    isInstance = isInstance && "folder" in value;
    isInstance = isInstance && "lastSync" in value;
    isInstance = isInstance && "syncStatus" in value;
    isInstance = isInstance && "commitHash" in value;

    return isInstance;
}

export function CustomPipelineSettingsFromJSON(json: any): CustomPipelineSettings {
    return CustomPipelineSettingsFromJSONTyped(json, false);
}

export function CustomPipelineSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomPipelineSettings {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'repository': json['repository'],
        'branch': json['branch'],
        'folder': json['folder'],
        'lastSync': (new Date(json['lastSync'])),
        'syncStatus': json['syncStatus'],
        'commitHash': json['commitHash'],
    };
}

export function CustomPipelineSettingsToJSON(value?: CustomPipelineSettings | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'repository': value.repository,
        'branch': value.branch,
        'folder': value.folder,
        'lastSync': (value.lastSync.toISOString()),
        'syncStatus': value.syncStatus,
        'commitHash': value.commitHash,
    };
}

