/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Tag } from './Tag';
import {
    TagFromJSON,
    TagFromJSONTyped,
    TagToJSON,
    TagToJSONTyped,
} from './Tag';

/**
 * 
 * @export
 * @interface DashboardInput
 */
export interface DashboardInput {
    /**
     * 
     * @type {string}
     * @memberof DashboardInput
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof DashboardInput
     */
    description: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof DashboardInput
     */
    dashboardData: { [key: string]: any; };
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof DashboardInput
     */
    criteria: { [key: string]: any; };
    /**
     * 
     * @type {Array<Tag>}
     * @memberof DashboardInput
     */
    tags: Array<Tag>;
    /**
     * 
     * @type {number}
     * @memberof DashboardInput
     */
    schemaVersion: number;
}

/**
 * Check if a given object implements the DashboardInput interface.
 */
export function instanceOfDashboardInput(value: object): value is DashboardInput {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('dashboardData' in value) || value['dashboardData'] === undefined) return false;
    if (!('criteria' in value) || value['criteria'] === undefined) return false;
    if (!('tags' in value) || value['tags'] === undefined) return false;
    if (!('schemaVersion' in value) || value['schemaVersion'] === undefined) return false;
    return true;
}

export function DashboardInputFromJSON(json: any): DashboardInput {
    return DashboardInputFromJSONTyped(json, false);
}

export function DashboardInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): DashboardInput {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
        'dashboardData': json['dashboardData'],
        'criteria': json['criteria'],
        'tags': ((json['tags'] as Array<any>).map(TagFromJSON)),
        'schemaVersion': json['schemaVersion'],
    };
}

export function DashboardInputToJSON(json: any): DashboardInput {
    return DashboardInputToJSONTyped(json, false);
}

export function DashboardInputToJSONTyped(value?: DashboardInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'dashboardData': value['dashboardData'],
        'criteria': value['criteria'],
        'tags': ((value['tags'] as Array<any>).map(TagToJSON)),
        'schemaVersion': value['schemaVersion'],
    };
}

