/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum DiscussionType {
    Discussion = 'DISCUSSION',
    Notes = 'NOTES'
}


export function instanceOfDiscussionType(value: any): boolean {
    for (const key in DiscussionType) {
        if (Object.prototype.hasOwnProperty.call(DiscussionType, key)) {
            if (DiscussionType[key as keyof typeof DiscussionType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DiscussionTypeFromJSON(json: any): DiscussionType {
    return DiscussionTypeFromJSONTyped(json, false);
}

export function DiscussionTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiscussionType {
    return json as DiscussionType;
}

export function DiscussionTypeToJSON(value?: DiscussionType | null): any {
    return value as any;
}

export function DiscussionTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): DiscussionType {
    return value as DiscussionType;
}

