/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Entity } from './Entity';
import {
    EntityFromJSON,
    EntityFromJSONTyped,
    EntityToJSON,
    EntityToJSONTyped,
} from './Entity';
import type { DiscussionType } from './DiscussionType';
import {
    DiscussionTypeFromJSON,
    DiscussionTypeFromJSONTyped,
    DiscussionTypeToJSON,
    DiscussionTypeToJSONTyped,
} from './DiscussionType';

/**
 * 
 * @export
 * @interface Discussion
 */
export interface Discussion {
    /**
     * 
     * @type {string}
     * @memberof Discussion
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Discussion
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Discussion
     */
    description: string;
    /**
     * 
     * @type {Entity}
     * @memberof Discussion
     */
    entity: Entity;
    /**
     * 
     * @type {DiscussionType}
     * @memberof Discussion
     */
    type: DiscussionType;
    /**
     * 
     * @type {string}
     * @memberof Discussion
     */
    projectId: string;
    /**
     * 
     * @type {string}
     * @memberof Discussion
     */
    createdBy: string;
    /**
     * 
     * @type {Date}
     * @memberof Discussion
     */
    lastMessageTime?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof Discussion
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Discussion
     */
    updatedAt: Date;
}



/**
 * Check if a given object implements the Discussion interface.
 */
export function instanceOfDiscussion(value: object): value is Discussion {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('entity' in value) || value['entity'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function DiscussionFromJSON(json: any): Discussion {
    return DiscussionFromJSONTyped(json, false);
}

export function DiscussionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Discussion {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'],
        'entity': EntityFromJSON(json['entity']),
        'type': DiscussionTypeFromJSON(json['type']),
        'projectId': json['projectId'],
        'createdBy': json['createdBy'],
        'lastMessageTime': json['lastMessageTime'] == null ? undefined : (new Date(json['lastMessageTime'])),
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function DiscussionToJSON(json: any): Discussion {
    return DiscussionToJSONTyped(json, false);
}

export function DiscussionToJSONTyped(value?: Discussion | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'entity': EntityToJSON(value['entity']),
        'type': DiscussionTypeToJSON(value['type']),
        'projectId': value['projectId'],
        'createdBy': value['createdBy'],
        'lastMessageTime': value['lastMessageTime'] == null ? value['lastMessageTime'] : value['lastMessageTime'].toISOString(),
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}

