/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FileEntry
 */
export interface FileEntry {
    /**
     * Relative path to file
     * @type {string}
     * @memberof FileEntry
     */
    path?: string;
    /**
     * File size (in bytes)
     * @type {number}
     * @memberof FileEntry
     */
    size?: number;
    /**
     * Metadata associated with the file
     * @type {{ [key: string]: string; }}
     * @memberof FileEntry
     */
    metadata?: { [key: string]: string; };
}

/**
 * Check if a given object implements the FileEntry interface.
 */
export function instanceOfFileEntry(value: object): value is FileEntry {
    return true;
}

export function FileEntryFromJSON(json: any): FileEntry {
    return FileEntryFromJSONTyped(json, false);
}

export function FileEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'path': json['path'] == null ? undefined : json['path'],
        'size': json['size'] == null ? undefined : json['size'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function FileEntryToJSON(json: any): FileEntry {
    return FileEntryToJSONTyped(json, false);
}

export function FileEntryToJSONTyped(value?: FileEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'path': value['path'],
        'size': value['size'],
        'metadata': value['metadata'],
    };
}

