/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FileEntry
 */
export interface FileEntry {
    /**
     * Relative path to file
     * @type {string}
     * @memberof FileEntry
     */
    path?: string;
    /**
     * File size (in bytes)
     * @type {number}
     * @memberof FileEntry
     */
    size?: number;
    /**
     * Metadata associated with the file
     * @type {{ [key: string]: string; }}
     * @memberof FileEntry
     */
    metadata?: { [key: string]: string; };
}

/**
 * Check if a given object implements the FileEntry interface.
 */
export function instanceOfFileEntry(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FileEntryFromJSON(json: any): FileEntry {
    return FileEntryFromJSONTyped(json, false);
}

export function FileEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileEntry {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'path': !exists(json, 'path') ? undefined : json['path'],
        'size': !exists(json, 'size') ? undefined : json['size'],
        'metadata': !exists(json, 'metadata') ? undefined : json['metadata'],
    };
}

export function FileEntryToJSON(value?: FileEntry | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'path': value.path,
        'size': value.size,
        'metadata': value.metadata,
    };
}

