/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Determines the file format used when passing the schema-validated input to the pipeline.
 *  - CSV: comma-delimited, one row per object, header row taken from the schema's property order.
 *    Nested objects/arrays within a row are JSON-encoded inline as a single cell value (not recommended).
 *  - TSV: same as CSV, but tab-delimited.
 *  - JSON: the row objects are written out unmodified as a JSON array (no flattening).
 * 
 * @export
 * @enum {string}
 */
export enum FileFormat {
    Csv = 'CSV',
    Tsv = 'TSV',
    Json = 'JSON'
}


export function instanceOfFileFormat(value: any): boolean {
    for (const key in FileFormat) {
        if (Object.prototype.hasOwnProperty.call(FileFormat, key)) {
            if (FileFormat[key as keyof typeof FileFormat] === value) {
                return true;
            }
        }
    }
    return false;
}

export function FileFormatFromJSON(json: any): FileFormat {
    return FileFormatFromJSONTyped(json, false);
}

export function FileFormatFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileFormat {
    return json as FileFormat;
}

export function FileFormatToJSON(value?: FileFormat | null): any {
    return value as any;
}

export function FileFormatToJSONTyped(value: any, ignoreDiscriminator: boolean): FileFormat {
    return value as FileFormat;
}

