/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FulfillmentResponse
 */
export interface FulfillmentResponse {
    /**
     * 
     * @type {string}
     * @memberof FulfillmentResponse
     */
    fulfillmentId: string;
    /**
     * 
     * @type {string}
     * @memberof FulfillmentResponse
     */
    path: string;
}

/**
 * Check if a given object implements the FulfillmentResponse interface.
 */
export function instanceOfFulfillmentResponse(value: object): value is FulfillmentResponse {
    if (!('fulfillmentId' in value) || value['fulfillmentId'] === undefined) return false;
    if (!('path' in value) || value['path'] === undefined) return false;
    return true;
}

export function FulfillmentResponseFromJSON(json: any): FulfillmentResponse {
    return FulfillmentResponseFromJSONTyped(json, false);
}

export function FulfillmentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FulfillmentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'fulfillmentId': json['fulfillmentId'],
        'path': json['path'],
    };
}

export function FulfillmentResponseToJSON(json: any): FulfillmentResponse {
    return FulfillmentResponseToJSONTyped(json, false);
}

export function FulfillmentResponseToJSONTyped(value?: FulfillmentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fulfillmentId': value['fulfillmentId'],
        'path': value['path'],
    };
}

