/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GovernanceExpiryType } from './GovernanceExpiryType';
import {
    GovernanceExpiryTypeFromJSON,
    GovernanceExpiryTypeFromJSONTyped,
    GovernanceExpiryTypeToJSON,
} from './GovernanceExpiryType';

/**
 * 
 * @export
 * @interface GovernanceExpiry
 */
export interface GovernanceExpiry {
    /**
     * 
     * @type {GovernanceExpiryType}
     * @memberof GovernanceExpiry
     */
    type?: GovernanceExpiryType;
    /**
     * The number of days for a relative expiration
     * @type {number}
     * @memberof GovernanceExpiry
     */
    days?: number | null;
    /**
     * The date for an absolute expiration
     * @type {Date}
     * @memberof GovernanceExpiry
     */
    date?: Date | null;
}

/**
 * Check if a given object implements the GovernanceExpiry interface.
 */
export function instanceOfGovernanceExpiry(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GovernanceExpiryFromJSON(json: any): GovernanceExpiry {
    return GovernanceExpiryFromJSONTyped(json, false);
}

export function GovernanceExpiryFromJSONTyped(json: any, ignoreDiscriminator: boolean): GovernanceExpiry {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : GovernanceExpiryTypeFromJSON(json['type']),
        'days': !exists(json, 'days') ? undefined : json['days'],
        'date': !exists(json, 'date') ? undefined : (json['date'] === null ? null : new Date(json['date'])),
    };
}

export function GovernanceExpiryToJSON(value?: GovernanceExpiry | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': GovernanceExpiryTypeToJSON(value.type),
        'days': value.days,
        'date': value.date === undefined ? undefined : (value.date === null ? null : value.date.toISOString()),
    };
}

