/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The options for supplementals for governance requirements
 * @export
 * @enum {string}
 */
export enum GovernanceFileType {
    File = 'FILE',
    Link = 'LINK'
}


export function GovernanceFileTypeFromJSON(json: any): GovernanceFileType {
    return GovernanceFileTypeFromJSONTyped(json, false);
}

export function GovernanceFileTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): GovernanceFileType {
    return json as GovernanceFileType;
}

export function GovernanceFileTypeToJSON(value?: GovernanceFileType | null): any {
    return value as any;
}

