/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum JoinType {
    Inner = 'INNER',
    Left = 'LEFT',
    Right = 'RIGHT',
    Full = 'FULL'
}


export function JoinTypeFromJSON(json: any): JoinType {
    return JoinTypeFromJSONTyped(json, false);
}

export function JoinTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoinType {
    return json as JoinType;
}

export function JoinTypeToJSON(value?: JoinType | null): any {
    return value as any;
}

