/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginProvider
 */
export interface LoginProvider {
    /**
     * 
     * @type {string}
     * @memberof LoginProvider
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof LoginProvider
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof LoginProvider
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof LoginProvider
     */
    logoUrl: string;
}

/**
 * Check if a given object implements the LoginProvider interface.
 */
export function instanceOfLoginProvider(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "logoUrl" in value;

    return isInstance;
}

export function LoginProviderFromJSON(json: any): LoginProvider {
    return LoginProviderFromJSONTyped(json, false);
}

export function LoginProviderFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginProvider {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'],
        'logoUrl': json['logoUrl'],
    };
}

export function LoginProviderToJSON(value?: LoginProvider | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'description': value.description,
        'logoUrl': value.logoUrl,
    };
}

