/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MessageInput
 */
export interface MessageInput {
    /**
     * 
     * @type {string}
     * @memberof MessageInput
     */
    parentMessageId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MessageInput
     */
    message: string;
}

/**
 * Check if a given object implements the MessageInput interface.
 */
export function instanceOfMessageInput(value: object): value is MessageInput {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function MessageInputFromJSON(json: any): MessageInput {
    return MessageInputFromJSONTyped(json, false);
}

export function MessageInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageInput {
    if (json == null) {
        return json;
    }
    return {
        
        'parentMessageId': json['parentMessageId'] == null ? undefined : json['parentMessageId'],
        'message': json['message'],
    };
}

export function MessageInputToJSON(json: any): MessageInput {
    return MessageInputToJSONTyped(json, false);
}

export function MessageInputToJSONTyped(value?: MessageInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'parentMessageId': value['parentMessageId'],
        'message': value['message'],
    };
}

