/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Represents a mounted dataset in a workspace
 * @export
 * @interface MountedDataset
 */
export interface MountedDataset {
    /**
     * Folder name that appears in the workspace
     * @type {string}
     * @memberof MountedDataset
     */
    name: string;
    /**
     * ID of the dataset to mount
     * @type {string}
     * @memberof MountedDataset
     */
    datasetId?: string | null;
    /**
     * Full S3 URI to mounted data (if mounting custom path)
     * @type {string}
     * @memberof MountedDataset
     */
    customUri?: string | null;
    /**
     * ID of a shared filesystem to mount (read-write)
     * @type {string}
     * @memberof MountedDataset
     */
    sharedFilesystemId?: string | null;
}

/**
 * Check if a given object implements the MountedDataset interface.
 */
export function instanceOfMountedDataset(value: object): value is MountedDataset {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function MountedDatasetFromJSON(json: any): MountedDataset {
    return MountedDatasetFromJSONTyped(json, false);
}

export function MountedDatasetFromJSONTyped(json: any, ignoreDiscriminator: boolean): MountedDataset {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'datasetId': json['datasetId'] == null ? undefined : json['datasetId'],
        'customUri': json['customUri'] == null ? undefined : json['customUri'],
        'sharedFilesystemId': json['sharedFilesystemId'] == null ? undefined : json['sharedFilesystemId'],
    };
}

export function MountedDatasetToJSON(json: any): MountedDataset {
    return MountedDatasetToJSONTyped(json, false);
}

export function MountedDatasetToJSONTyped(value?: MountedDataset | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'datasetId': value['datasetId'],
        'customUri': value['customUri'],
        'sharedFilesystemId': value['sharedFilesystemId'],
    };
}

