/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A Nextflow version supported by Cirro
 * @export
 * @enum {string}
 */
export enum NextflowVersion {
    V22_04_0 = '22.04.0',
    V23_10_0 = '23.10.0',
    V24_10_8 = '24.10.8',
    V25_10_0 = '25.10.0',
    V26_04_0 = '26.04.0'
}


export function instanceOfNextflowVersion(value: any): boolean {
    for (const key in NextflowVersion) {
        if (Object.prototype.hasOwnProperty.call(NextflowVersion, key)) {
            if (NextflowVersion[key as keyof typeof NextflowVersion] === value) {
                return true;
            }
        }
    }
    return false;
}

export function NextflowVersionFromJSON(json: any): NextflowVersion {
    return NextflowVersionFromJSONTyped(json, false);
}

export function NextflowVersionFromJSONTyped(json: any, ignoreDiscriminator: boolean): NextflowVersion {
    return json as NextflowVersion;
}

export function NextflowVersionToJSON(value?: NextflowVersion | null): any {
    return value as any;
}

export function NextflowVersionToJSONTyped(value: any, ignoreDiscriminator: boolean): NextflowVersion {
    return value as NextflowVersion;
}

