/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Discussion } from './Discussion';
import {
    DiscussionFromJSON,
    DiscussionFromJSONTyped,
    DiscussionToJSON,
} from './Discussion';

/**
 * 
 * @export
 * @interface PaginatedResponseDiscussion
 */
export interface PaginatedResponseDiscussion {
    /**
     * 
     * @type {Array<Discussion>}
     * @memberof PaginatedResponseDiscussion
     */
    data: Array<Discussion>;
    /**
     * 
     * @type {string}
     * @memberof PaginatedResponseDiscussion
     */
    nextToken: string;
}

/**
 * Check if a given object implements the PaginatedResponseDiscussion interface.
 */
export function instanceOfPaginatedResponseDiscussion(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "nextToken" in value;

    return isInstance;
}

export function PaginatedResponseDiscussionFromJSON(json: any): PaginatedResponseDiscussion {
    return PaginatedResponseDiscussionFromJSONTyped(json, false);
}

export function PaginatedResponseDiscussionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedResponseDiscussion {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(DiscussionFromJSON)),
        'nextToken': json['nextToken'],
    };
}

export function PaginatedResponseDiscussionToJSON(value?: PaginatedResponseDiscussion | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(DiscussionToJSON)),
        'nextToken': value.nextToken,
    };
}

