/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface PaginatedResponseUserDto
 */
export interface PaginatedResponseUserDto {
    /**
     * 
     * @type {Array<User>}
     * @memberof PaginatedResponseUserDto
     */
    data: Array<User>;
    /**
     * 
     * @type {string}
     * @memberof PaginatedResponseUserDto
     */
    nextToken: string;
}

/**
 * Check if a given object implements the PaginatedResponseUserDto interface.
 */
export function instanceOfPaginatedResponseUserDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "nextToken" in value;

    return isInstance;
}

export function PaginatedResponseUserDtoFromJSON(json: any): PaginatedResponseUserDto {
    return PaginatedResponseUserDtoFromJSONTyped(json, false);
}

export function PaginatedResponseUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedResponseUserDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(UserFromJSON)),
        'nextToken': json['nextToken'],
    };
}

export function PaginatedResponseUserDtoToJSON(value?: PaginatedResponseUserDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(UserToJSON)),
        'nextToken': value.nextToken,
    };
}

