/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProcessRevision } from './ProcessRevision';
import {
    ProcessRevisionFromJSON,
    ProcessRevisionFromJSONTyped,
    ProcessRevisionToJSON,
    ProcessRevisionToJSONTyped,
} from './ProcessRevision';

/**
 * 
 * @export
 * @interface PaginatedResponseProcessRevisionDto
 */
export interface PaginatedResponseProcessRevisionDto {
    /**
     * 
     * @type {Array<ProcessRevision>}
     * @memberof PaginatedResponseProcessRevisionDto
     */
    data: Array<ProcessRevision>;
    /**
     * 
     * @type {string}
     * @memberof PaginatedResponseProcessRevisionDto
     */
    nextToken: string;
}

/**
 * Check if a given object implements the PaginatedResponseProcessRevisionDto interface.
 */
export function instanceOfPaginatedResponseProcessRevisionDto(value: object): value is PaginatedResponseProcessRevisionDto {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('nextToken' in value) || value['nextToken'] === undefined) return false;
    return true;
}

export function PaginatedResponseProcessRevisionDtoFromJSON(json: any): PaginatedResponseProcessRevisionDto {
    return PaginatedResponseProcessRevisionDtoFromJSONTyped(json, false);
}

export function PaginatedResponseProcessRevisionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedResponseProcessRevisionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ProcessRevisionFromJSON)),
        'nextToken': json['nextToken'],
    };
}

export function PaginatedResponseProcessRevisionDtoToJSON(json: any): PaginatedResponseProcessRevisionDto {
    return PaginatedResponseProcessRevisionDtoToJSONTyped(json, false);
}

export function PaginatedResponseProcessRevisionDtoToJSONTyped(value?: PaginatedResponseProcessRevisionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(ProcessRevisionToJSON)),
        'nextToken': value['nextToken'],
    };
}

