/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Resource type for this saved file.
 * @export
 * @enum {string}
 */
export enum ProcessResource {
    Form = 'form',
    Input = 'input',
    Output = 'output',
    Compute = 'compute',
    Preprocess = 'preprocess',
    Metadata = 'metadata',
    Documentation = 'documentation'
}


export function instanceOfProcessResource(value: any): boolean {
    for (const key in ProcessResource) {
        if (Object.prototype.hasOwnProperty.call(ProcessResource, key)) {
            if (ProcessResource[key as keyof typeof ProcessResource] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ProcessResourceFromJSON(json: any): ProcessResource {
    return ProcessResourceFromJSONTyped(json, false);
}

export function ProcessResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcessResource {
    return json as ProcessResource;
}

export function ProcessResourceToJSON(value?: ProcessResource | null): any {
    return value as any;
}

export function ProcessResourceToJSONTyped(value: any, ignoreDiscriminator: boolean): ProcessResource {
    return value as ProcessResource;
}

