/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Executor } from './Executor';
import {
    ExecutorFromJSON,
    ExecutorFromJSONTyped,
    ExecutorToJSON,
    ExecutorToJSONTyped,
} from './Executor';
import type { FileMappingRule } from './FileMappingRule';
import {
    FileMappingRuleFromJSON,
    FileMappingRuleFromJSONTyped,
    FileMappingRuleToJSON,
    FileMappingRuleToJSONTyped,
} from './FileMappingRule';
import type { CustomPipelineSettings } from './CustomPipelineSettings';
import {
    CustomPipelineSettingsFromJSON,
    CustomPipelineSettingsFromJSONTyped,
    CustomPipelineSettingsToJSON,
    CustomPipelineSettingsToJSONTyped,
} from './CustomPipelineSettings';
import type { Tag } from './Tag';
import {
    TagFromJSON,
    TagFromJSONTyped,
    TagToJSON,
    TagToJSONTyped,
} from './Tag';
import type { PipelineCode } from './PipelineCode';
import {
    PipelineCodeFromJSON,
    PipelineCodeFromJSONTyped,
    PipelineCodeToJSON,
    PipelineCodeToJSONTyped,
} from './PipelineCode';

/**
 * Identifies a data type or pipeline in Cirro
 * @export
 * @interface ProcessDetail
 */
export interface ProcessDetail {
    /**
     * Unique ID of the Process
     * @type {string}
     * @memberof ProcessDetail
     */
    id: string;
    /**
     * Friendly name for the process
     * @type {string}
     * @memberof ProcessDetail
     */
    name: string;
    /**
     * Description of the process
     * @type {string}
     * @memberof ProcessDetail
     */
    description: string;
    /**
     * Name of the data type this pipeline produces (if it is not defined, use the name)
     * @type {string}
     * @memberof ProcessDetail
     */
    dataType: string;
    /**
     * 
     * @type {Executor}
     * @memberof ProcessDetail
     */
    executor: Executor;
    /**
     * Category of the process
     * @type {string}
     * @memberof ProcessDetail
     */
    category?: string;
    /**
     * Type of pipeline
     * @type {string}
     * @memberof ProcessDetail
     */
    pipelineType?: string;
    /**
     * IDs of pipelines that can be run downstream
     * @type {Array<string>}
     * @memberof ProcessDetail
     */
    childProcessIds: Array<string>;
    /**
     * IDs of processes that can run this pipeline
     * @type {Array<string>}
     * @memberof ProcessDetail
     */
    parentProcessIds: Array<string>;
    /**
     * Link to process documentation
     * @type {string}
     * @memberof ProcessDetail
     */
    documentationUrl?: string;
    /**
     * Description of the files to be uploaded (optional)
     * @type {string}
     * @memberof ProcessDetail
     */
    fileRequirementsMessage?: string;
    /**
     * 
     * @type {PipelineCode}
     * @memberof ProcessDetail
     */
    pipelineCode?: PipelineCode | null;
    /**
     * Username of the pipeline creator (blank if Cirro curated)
     * @type {string}
     * @memberof ProcessDetail
     */
    owner?: string | null;
    /**
     * Projects that can run this process
     * @type {Array<string>}
     * @memberof ProcessDetail
     */
    linkedProjectIds: Array<string>;
    /**
     * Whether the process is shared with the tenant
     * @type {boolean}
     * @memberof ProcessDetail
     */
    isTenantWide: boolean;
    /**
     * Whether the pipeline is allowed to have multiple dataset sources
     * @type {boolean}
     * @memberof ProcessDetail
     */
    allowMultipleSources: boolean;
    /**
     * Whether the pipeline uses the Cirro-provided sample sheet
     * @type {boolean}
     * @memberof ProcessDetail
     */
    usesSampleSheet: boolean;
    /**
     * Whether the process is marked as archived
     * @type {boolean}
     * @memberof ProcessDetail
     */
    isArchived: boolean;
    /**
     * 
     * @type {CustomPipelineSettings}
     * @memberof ProcessDetail
     */
    customSettings?: CustomPipelineSettings | null;
    /**
     * 
     * @type {Array<FileMappingRule>}
     * @memberof ProcessDetail
     */
    fileMappingRules?: Array<FileMappingRule> | null;
    /**
     * When the process was created (does not reflect the pipeline code)
     * @type {Date}
     * @memberof ProcessDetail
     */
    createdAt?: Date;
    /**
     * When the process was updated (does not reflect the pipeline code)
     * @type {Date}
     * @memberof ProcessDetail
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Array<Tag>}
     * @memberof ProcessDetail
     */
    tags: Array<Tag>;
}



/**
 * Check if a given object implements the ProcessDetail interface.
 */
export function instanceOfProcessDetail(value: object): value is ProcessDetail {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('dataType' in value) || value['dataType'] === undefined) return false;
    if (!('executor' in value) || value['executor'] === undefined) return false;
    if (!('childProcessIds' in value) || value['childProcessIds'] === undefined) return false;
    if (!('parentProcessIds' in value) || value['parentProcessIds'] === undefined) return false;
    if (!('linkedProjectIds' in value) || value['linkedProjectIds'] === undefined) return false;
    if (!('isTenantWide' in value) || value['isTenantWide'] === undefined) return false;
    if (!('allowMultipleSources' in value) || value['allowMultipleSources'] === undefined) return false;
    if (!('usesSampleSheet' in value) || value['usesSampleSheet'] === undefined) return false;
    if (!('isArchived' in value) || value['isArchived'] === undefined) return false;
    if (!('tags' in value) || value['tags'] === undefined) return false;
    return true;
}

export function ProcessDetailFromJSON(json: any): ProcessDetail {
    return ProcessDetailFromJSONTyped(json, false);
}

export function ProcessDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcessDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'],
        'dataType': json['dataType'],
        'executor': ExecutorFromJSON(json['executor']),
        'category': json['category'] == null ? undefined : json['category'],
        'pipelineType': json['pipelineType'] == null ? undefined : json['pipelineType'],
        'childProcessIds': json['childProcessIds'],
        'parentProcessIds': json['parentProcessIds'],
        'documentationUrl': json['documentationUrl'] == null ? undefined : json['documentationUrl'],
        'fileRequirementsMessage': json['fileRequirementsMessage'] == null ? undefined : json['fileRequirementsMessage'],
        'pipelineCode': json['pipelineCode'] == null ? undefined : PipelineCodeFromJSON(json['pipelineCode']),
        'owner': json['owner'] == null ? undefined : json['owner'],
        'linkedProjectIds': json['linkedProjectIds'],
        'isTenantWide': json['isTenantWide'],
        'allowMultipleSources': json['allowMultipleSources'],
        'usesSampleSheet': json['usesSampleSheet'],
        'isArchived': json['isArchived'],
        'customSettings': json['customSettings'] == null ? undefined : CustomPipelineSettingsFromJSON(json['customSettings']),
        'fileMappingRules': json['fileMappingRules'] == null ? undefined : ((json['fileMappingRules'] as Array<any>).map(FileMappingRuleFromJSON)),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'tags': ((json['tags'] as Array<any>).map(TagFromJSON)),
    };
}

export function ProcessDetailToJSON(json: any): ProcessDetail {
    return ProcessDetailToJSONTyped(json, false);
}

export function ProcessDetailToJSONTyped(value?: ProcessDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'dataType': value['dataType'],
        'executor': ExecutorToJSON(value['executor']),
        'category': value['category'],
        'pipelineType': value['pipelineType'],
        'childProcessIds': value['childProcessIds'],
        'parentProcessIds': value['parentProcessIds'],
        'documentationUrl': value['documentationUrl'],
        'fileRequirementsMessage': value['fileRequirementsMessage'],
        'pipelineCode': PipelineCodeToJSON(value['pipelineCode']),
        'owner': value['owner'],
        'linkedProjectIds': value['linkedProjectIds'],
        'isTenantWide': value['isTenantWide'],
        'allowMultipleSources': value['allowMultipleSources'],
        'usesSampleSheet': value['usesSampleSheet'],
        'isArchived': value['isArchived'],
        'customSettings': CustomPipelineSettingsToJSON(value['customSettings']),
        'fileMappingRules': value['fileMappingRules'] == null ? undefined : ((value['fileMappingRules'] as Array<any>).map(FileMappingRuleToJSON)),
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'tags': ((value['tags'] as Array<any>).map(TagToJSON)),
    };
}

