/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectPermissionSet
 */
export interface ProjectPermissionSet {
    /**
     * 
     * @type {string}
     * @memberof ProjectPermissionSet
     */
    projectId: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProjectPermissionSet
     */
    permissions: Array<string>;
}

/**
 * Check if a given object implements the ProjectPermissionSet interface.
 */
export function instanceOfProjectPermissionSet(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "projectId" in value;
    isInstance = isInstance && "permissions" in value;

    return isInstance;
}

export function ProjectPermissionSetFromJSON(json: any): ProjectPermissionSet {
    return ProjectPermissionSetFromJSONTyped(json, false);
}

export function ProjectPermissionSetFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectPermissionSet {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'projectId': json['projectId'],
        'permissions': json['permissions'],
    };
}

export function ProjectPermissionSetToJSON(value?: ProjectPermissionSet | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'projectId': value.projectId,
        'permissions': value.permissions,
    };
}

