/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CloudAccount } from './CloudAccount';
import {
    CloudAccountFromJSON,
    CloudAccountFromJSONTyped,
    CloudAccountToJSON,
    CloudAccountToJSONTyped,
} from './CloudAccount';
import type { Tag } from './Tag';
import {
    TagFromJSON,
    TagFromJSONTyped,
    TagToJSON,
    TagToJSONTyped,
} from './Tag';
import type { Contact } from './Contact';
import {
    ContactFromJSON,
    ContactFromJSONTyped,
    ContactToJSON,
    ContactToJSONTyped,
} from './Contact';
import type { ProjectSettings } from './ProjectSettings';
import {
    ProjectSettingsFromJSON,
    ProjectSettingsFromJSONTyped,
    ProjectSettingsToJSON,
    ProjectSettingsToJSONTyped,
} from './ProjectSettings';

/**
 * 
 * @export
 * @interface ProjectInput
 */
export interface ProjectInput {
    /**
     * 
     * @type {string}
     * @memberof ProjectInput
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectInput
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectInput
     */
    billingAccountId: string;
    /**
     * 
     * @type {ProjectSettings}
     * @memberof ProjectInput
     */
    settings: ProjectSettings;
    /**
     * 
     * @type {Array<Contact>}
     * @memberof ProjectInput
     */
    contacts: Array<Contact>;
    /**
     * 
     * @type {CloudAccount}
     * @memberof ProjectInput
     */
    account?: CloudAccount | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProjectInput
     */
    classificationIds?: Array<string> | null;
    /**
     * 
     * @type {Array<Tag>}
     * @memberof ProjectInput
     */
    tags?: Array<Tag> | null;
}

/**
 * Check if a given object implements the ProjectInput interface.
 */
export function instanceOfProjectInput(value: object): value is ProjectInput {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('billingAccountId' in value) || value['billingAccountId'] === undefined) return false;
    if (!('settings' in value) || value['settings'] === undefined) return false;
    if (!('contacts' in value) || value['contacts'] === undefined) return false;
    return true;
}

export function ProjectInputFromJSON(json: any): ProjectInput {
    return ProjectInputFromJSONTyped(json, false);
}

export function ProjectInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectInput {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
        'billingAccountId': json['billingAccountId'],
        'settings': ProjectSettingsFromJSON(json['settings']),
        'contacts': ((json['contacts'] as Array<any>).map(ContactFromJSON)),
        'account': json['account'] == null ? undefined : CloudAccountFromJSON(json['account']),
        'classificationIds': json['classificationIds'] == null ? undefined : json['classificationIds'],
        'tags': json['tags'] == null ? undefined : ((json['tags'] as Array<any>).map(TagFromJSON)),
    };
}

export function ProjectInputToJSON(json: any): ProjectInput {
    return ProjectInputToJSONTyped(json, false);
}

export function ProjectInputToJSONTyped(value?: ProjectInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'billingAccountId': value['billingAccountId'],
        'settings': ProjectSettingsToJSON(value['settings']),
        'contacts': ((value['contacts'] as Array<any>).map(ContactToJSON)),
        'account': CloudAccountToJSON(value['account']),
        'classificationIds': value['classificationIds'],
        'tags': value['tags'] == null ? undefined : ((value['tags'] as Array<any>).map(TagToJSON)),
    };
}

