/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BudgetPeriod } from './BudgetPeriod';
import {
    BudgetPeriodFromJSON,
    BudgetPeriodFromJSONTyped,
    BudgetPeriodToJSON,
} from './BudgetPeriod';

/**
 * 
 * @export
 * @interface ProjectSettings
 */
export interface ProjectSettings {
    /**
     * Total allowed cost for the budget period
     * @type {number}
     * @memberof ProjectSettings
     */
    budgetAmount: number;
    /**
     * 
     * @type {BudgetPeriod}
     * @memberof ProjectSettings
     */
    budgetPeriod: BudgetPeriod;
    /**
     * Enables the AWS Backup service for S3
     * @type {boolean}
     * @memberof ProjectSettings
     */
    enableBackup?: boolean;
    /**
     * Enables access to files over SFTP
     * @type {boolean}
     * @memberof ProjectSettings
     */
    enableSftp?: boolean;
    /**
     * List of service connections to enable
     * @type {Array<string>}
     * @memberof ProjectSettings
     */
    serviceConnections?: Array<string>;
    /**
     * KMS Key ARN to encrypt S3 objects, if not provided, default bucket encryption will be used
     * @type {string}
     * @memberof ProjectSettings
     */
    kmsArn?: string | null;
    /**
     * Days to keep deleted datasets before being permanently erased
     * @type {number}
     * @memberof ProjectSettings
     */
    retentionPolicyDays?: number;
    /**
     * Days to keep temporary storage space (workflow executor cache)
     * @type {number}
     * @memberof ProjectSettings
     */
    temporaryStorageLifetimeDays?: number;
    /**
     * VPC that the compute environment will use
     * @type {string}
     * @memberof ProjectSettings
     */
    vpcId?: string | null;
    /**
     * List of subnets that the pipeline compute environment will use
     * @type {Array<string>}
     * @memberof ProjectSettings
     */
    batchSubnets?: Array<string> | null;
    /**
     * List of subnets that the sagemaker instances will use
     * @type {Array<string>}
     * @memberof ProjectSettings
     * @deprecated
     */
    sagemakerSubnets?: Array<string> | null;
    /**
     * List of subnets that workspace instances will use
     * @type {Array<string>}
     * @memberof ProjectSettings
     */
    workspaceSubnets?: Array<string> | null;
    /**
     * vCPU service quota limit for standard spot instances (pipelines)
     * @type {number}
     * @memberof ProjectSettings
     */
    maxSpotVCPU?: number;
    /**
     * vCPU service quota limit for FPGA-enabled instances (pipelines)
     * @type {number}
     * @memberof ProjectSettings
     */
    maxFPGAVCPU?: number;
    /**
     * vCPU service quota limit for GPU-enabled spot instances (pipelines)
     * @type {number}
     * @memberof ProjectSettings
     */
    maxGPUVCPU?: number;
    /**
     * Enables the DRAGEN compute environment (pipelines)
     * @type {boolean}
     * @memberof ProjectSettings
     */
    enableDragen?: boolean;
    /**
     * AMI ID for the DRAGEN compute environment, if enabled (pipelines)
     * @type {string}
     * @memberof ProjectSettings
     */
    dragenAmi?: string | null;
    /**
     * vCPU service quota limit for standard instances (workspaces)
     * @type {number}
     * @memberof ProjectSettings
     */
    maxWorkspacesVCPU?: number;
    /**
     * vCPU service quota limit for GPU-enabled instances (workspaces)
     * @type {number}
     * @memberof ProjectSettings
     */
    maxWorkspacesGPUVCPU?: number;
    /**
     * Maximum number of workspaces per user (workspaces)
     * @type {number}
     * @memberof ProjectSettings
     */
    maxWorkspacesPerUser?: number;
    /**
     * Enables the project to be discoverable by other users
     * @type {boolean}
     * @memberof ProjectSettings
     */
    isDiscoverable?: boolean | null;
    /**
     * Enables the project to be shared with other projects
     * @type {boolean}
     * @memberof ProjectSettings
     */
    isShareable?: boolean | null;
    /**
     * (Read-only) Whether this project has pipelines enabled
     * @type {boolean}
     * @memberof ProjectSettings
     */
    hasPipelinesEnabled?: boolean | null;
    /**
     * (Read-only) Whether this project has workspaces enabled
     * @type {boolean}
     * @memberof ProjectSettings
     */
    hasWorkspacesEnabled?: boolean | null;
}

/**
 * Check if a given object implements the ProjectSettings interface.
 */
export function instanceOfProjectSettings(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "budgetAmount" in value;
    isInstance = isInstance && "budgetPeriod" in value;

    return isInstance;
}

export function ProjectSettingsFromJSON(json: any): ProjectSettings {
    return ProjectSettingsFromJSONTyped(json, false);
}

export function ProjectSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectSettings {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'budgetAmount': json['budgetAmount'],
        'budgetPeriod': BudgetPeriodFromJSON(json['budgetPeriod']),
        'enableBackup': !exists(json, 'enableBackup') ? undefined : json['enableBackup'],
        'enableSftp': !exists(json, 'enableSftp') ? undefined : json['enableSftp'],
        'serviceConnections': !exists(json, 'serviceConnections') ? undefined : json['serviceConnections'],
        'kmsArn': !exists(json, 'kmsArn') ? undefined : json['kmsArn'],
        'retentionPolicyDays': !exists(json, 'retentionPolicyDays') ? undefined : json['retentionPolicyDays'],
        'temporaryStorageLifetimeDays': !exists(json, 'temporaryStorageLifetimeDays') ? undefined : json['temporaryStorageLifetimeDays'],
        'vpcId': !exists(json, 'vpcId') ? undefined : json['vpcId'],
        'batchSubnets': !exists(json, 'batchSubnets') ? undefined : json['batchSubnets'],
        'sagemakerSubnets': !exists(json, 'sagemakerSubnets') ? undefined : json['sagemakerSubnets'],
        'workspaceSubnets': !exists(json, 'workspaceSubnets') ? undefined : json['workspaceSubnets'],
        'maxSpotVCPU': !exists(json, 'maxSpotVCPU') ? undefined : json['maxSpotVCPU'],
        'maxFPGAVCPU': !exists(json, 'maxFPGAVCPU') ? undefined : json['maxFPGAVCPU'],
        'maxGPUVCPU': !exists(json, 'maxGPUVCPU') ? undefined : json['maxGPUVCPU'],
        'enableDragen': !exists(json, 'enableDragen') ? undefined : json['enableDragen'],
        'dragenAmi': !exists(json, 'dragenAmi') ? undefined : json['dragenAmi'],
        'maxWorkspacesVCPU': !exists(json, 'maxWorkspacesVCPU') ? undefined : json['maxWorkspacesVCPU'],
        'maxWorkspacesGPUVCPU': !exists(json, 'maxWorkspacesGPUVCPU') ? undefined : json['maxWorkspacesGPUVCPU'],
        'maxWorkspacesPerUser': !exists(json, 'maxWorkspacesPerUser') ? undefined : json['maxWorkspacesPerUser'],
        'isDiscoverable': !exists(json, 'isDiscoverable') ? undefined : json['isDiscoverable'],
        'isShareable': !exists(json, 'isShareable') ? undefined : json['isShareable'],
        'hasPipelinesEnabled': !exists(json, 'hasPipelinesEnabled') ? undefined : json['hasPipelinesEnabled'],
        'hasWorkspacesEnabled': !exists(json, 'hasWorkspacesEnabled') ? undefined : json['hasWorkspacesEnabled'],
    };
}

export function ProjectSettingsToJSON(value?: ProjectSettings | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'budgetAmount': value.budgetAmount,
        'budgetPeriod': BudgetPeriodToJSON(value.budgetPeriod),
        'enableBackup': value.enableBackup,
        'enableSftp': value.enableSftp,
        'serviceConnections': value.serviceConnections,
        'kmsArn': value.kmsArn,
        'retentionPolicyDays': value.retentionPolicyDays,
        'temporaryStorageLifetimeDays': value.temporaryStorageLifetimeDays,
        'vpcId': value.vpcId,
        'batchSubnets': value.batchSubnets,
        'sagemakerSubnets': value.sagemakerSubnets,
        'workspaceSubnets': value.workspaceSubnets,
        'maxSpotVCPU': value.maxSpotVCPU,
        'maxFPGAVCPU': value.maxFPGAVCPU,
        'maxGPUVCPU': value.maxGPUVCPU,
        'enableDragen': value.enableDragen,
        'dragenAmi': value.dragenAmi,
        'maxWorkspacesVCPU': value.maxWorkspacesVCPU,
        'maxWorkspacesGPUVCPU': value.maxWorkspacesGPUVCPU,
        'maxWorkspacesPerUser': value.maxWorkspacesPerUser,
        'isDiscoverable': value.isDiscoverable,
        'isShareable': value.isShareable,
        'hasPipelinesEnabled': value.hasPipelinesEnabled,
        'hasWorkspacesEnabled': value.hasWorkspacesEnabled,
    };
}

