/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BudgetPeriod } from './BudgetPeriod';
import {
    BudgetPeriodFromJSON,
    BudgetPeriodFromJSONTyped,
    BudgetPeriodToJSON,
} from './BudgetPeriod';

/**
 * 
 * @export
 * @interface ProjectSettings
 */
export interface ProjectSettings {
    /**
     * 
     * @type {string}
     * @memberof ProjectSettings
     */
    budgetAmount?: string;
    /**
     * 
     * @type {BudgetPeriod}
     * @memberof ProjectSettings
     */
    budgetPeriod?: BudgetPeriod;
    /**
     * 
     * @type {string}
     * @memberof ProjectSettings
     */
    dragenAmi?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ProjectSettings
     */
    enableBackup?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ProjectSettings
     */
    enableCompute?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ProjectSettings
     */
    enableDragen?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ProjectSettings
     */
    enableSftp?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ProjectSettings
     */
    maxF1VCPU?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectSettings
     */
    maxSpotVCPU?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectSettings
     */
    retentionPolicyDays?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProjectSettings
     */
    serviceConnections?: Array<string>;
}

/**
 * Check if a given object implements the ProjectSettings interface.
 */
export function instanceOfProjectSettings(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProjectSettingsFromJSON(json: any): ProjectSettings {
    return ProjectSettingsFromJSONTyped(json, false);
}

export function ProjectSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectSettings {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'budgetAmount': !exists(json, 'budgetAmount') ? undefined : json['budgetAmount'],
        'budgetPeriod': !exists(json, 'budgetPeriod') ? undefined : BudgetPeriodFromJSON(json['budgetPeriod']),
        'dragenAmi': !exists(json, 'dragenAmi') ? undefined : json['dragenAmi'],
        'enableBackup': !exists(json, 'enableBackup') ? undefined : json['enableBackup'],
        'enableCompute': !exists(json, 'enableCompute') ? undefined : json['enableCompute'],
        'enableDragen': !exists(json, 'enableDragen') ? undefined : json['enableDragen'],
        'enableSftp': !exists(json, 'enableSftp') ? undefined : json['enableSftp'],
        'maxF1VCPU': !exists(json, 'maxF1VCPU') ? undefined : json['maxF1VCPU'],
        'maxSpotVCPU': !exists(json, 'maxSpotVCPU') ? undefined : json['maxSpotVCPU'],
        'retentionPolicyDays': !exists(json, 'retentionPolicyDays') ? undefined : json['retentionPolicyDays'],
        'serviceConnections': !exists(json, 'serviceConnections') ? undefined : json['serviceConnections'],
    };
}

export function ProjectSettingsToJSON(value?: ProjectSettings | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'budgetAmount': value.budgetAmount,
        'budgetPeriod': BudgetPeriodToJSON(value.budgetPeriod),
        'dragenAmi': value.dragenAmi,
        'enableBackup': value.enableBackup,
        'enableCompute': value.enableCompute,
        'enableDragen': value.enableDragen,
        'enableSftp': value.enableSftp,
        'maxF1VCPU': value.maxF1VCPU,
        'maxSpotVCPU': value.maxSpotVCPU,
        'retentionPolicyDays': value.retentionPolicyDays,
        'serviceConnections': value.serviceConnections,
    };
}

