/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectRole } from './ProjectRole';
import {
    ProjectRoleFromJSON,
    ProjectRoleFromJSONTyped,
    ProjectRoleToJSON,
    ProjectRoleToJSONTyped,
} from './ProjectRole';

/**
 * 
 * @export
 * @interface ProjectUser
 */
export interface ProjectUser {
    /**
     * 
     * @type {string}
     * @memberof ProjectUser
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectUser
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectUser
     */
    organization: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectUser
     */
    department: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectUser
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectUser
     */
    jobTitle: string;
    /**
     * 
     * @type {ProjectRole}
     * @memberof ProjectUser
     */
    role: ProjectRole;
}



/**
 * Check if a given object implements the ProjectUser interface.
 */
export function instanceOfProjectUser(value: object): value is ProjectUser {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('organization' in value) || value['organization'] === undefined) return false;
    if (!('department' in value) || value['department'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('jobTitle' in value) || value['jobTitle'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function ProjectUserFromJSON(json: any): ProjectUser {
    return ProjectUserFromJSONTyped(json, false);
}

export function ProjectUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectUser {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'username': json['username'],
        'organization': json['organization'],
        'department': json['department'],
        'email': json['email'],
        'jobTitle': json['jobTitle'],
        'role': ProjectRoleFromJSON(json['role']),
    };
}

export function ProjectUserToJSON(json: any): ProjectUser {
    return ProjectUserToJSONTyped(json, false);
}

export function ProjectUserToJSONTyped(value?: ProjectUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'username': value['username'],
        'organization': value['organization'],
        'department': value['department'],
        'email': value['email'],
        'jobTitle': value['jobTitle'],
        'role': ProjectRoleToJSON(value['role']),
    };
}

