/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RowUpdate
 */
export interface RowUpdate {
    /**
     * _row_id, which serves as the primary key to identify the row.
     * @type {number}
     * @memberof RowUpdate
     */
    rowId: number;
    /**
     * Column name and new value. Only the columns included here are updated; all other columns on the row are left unchanged. At least one entry is required.
     * @type {{ [key: string]: object; }}
     * @memberof RowUpdate
     */
    values: { [key: string]: object; };
}

/**
 * Check if a given object implements the RowUpdate interface.
 */
export function instanceOfRowUpdate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "rowId" in value;
    isInstance = isInstance && "values" in value;

    return isInstance;
}

export function RowUpdateFromJSON(json: any): RowUpdate {
    return RowUpdateFromJSONTyped(json, false);
}

export function RowUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): RowUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rowId': json['rowId'],
        'values': json['values'],
    };
}

export function RowUpdateToJSON(value?: RowUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rowId': value.rowId,
        'values': value.values,
    };
}

