/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RunAnalysisRequest
 */
export interface RunAnalysisRequest {
    /**
     * 
     * @type {string}
     * @memberof RunAnalysisRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof RunAnalysisRequest
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof RunAnalysisRequest
     */
    processId: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof RunAnalysisRequest
     */
    sourceDatasetIds: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof RunAnalysisRequest
     */
    resumeDatasetId: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof RunAnalysisRequest
     */
    params: { [key: string]: any; };
    /**
     * 
     * @type {Array<string>}
     * @memberof RunAnalysisRequest
     */
    notificationEmails: Array<string>;
}

/**
 * Check if a given object implements the RunAnalysisRequest interface.
 */
export function instanceOfRunAnalysisRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "processId" in value;
    isInstance = isInstance && "sourceDatasetIds" in value;
    isInstance = isInstance && "resumeDatasetId" in value;
    isInstance = isInstance && "params" in value;
    isInstance = isInstance && "notificationEmails" in value;

    return isInstance;
}

export function RunAnalysisRequestFromJSON(json: any): RunAnalysisRequest {
    return RunAnalysisRequestFromJSONTyped(json, false);
}

export function RunAnalysisRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RunAnalysisRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
        'processId': json['processId'],
        'sourceDatasetIds': json['sourceDatasetIds'],
        'resumeDatasetId': json['resumeDatasetId'],
        'params': json['params'],
        'notificationEmails': json['notificationEmails'],
    };
}

export function RunAnalysisRequestToJSON(value?: RunAnalysisRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'processId': value.processId,
        'sourceDatasetIds': value.sourceDatasetIds,
        'resumeDatasetId': value.resumeDatasetId,
        'params': value.params,
        'notificationEmails': value.notificationEmails,
    };
}

