/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProcessResource } from './ProcessResource';
import {
    ProcessResourceFromJSON,
    ProcessResourceFromJSONTyped,
    ProcessResourceToJSON,
    ProcessResourceToJSONTyped,
} from './ProcessResource';

/**
 * 
 * @export
 * @interface SavedProcessRevision
 */
export interface SavedProcessRevision {
    /**
     * Resource type for this saved file.
     * @type {ProcessResource}
     * @memberof SavedProcessRevision
     */
    type?: ProcessResource;
    /**
     * S3 URI of the content-addressed object written for this resource.
     * @type {string}
     * @memberof SavedProcessRevision
     */
    uri?: string;
    /**
     * Hex-encoded SHA-256 of the file content. Also used as the leaf segment of the S3 key.
     * @type {string}
     * @memberof SavedProcessRevision
     */
    contentSha256?: string;
}



/**
 * Check if a given object implements the SavedProcessRevision interface.
 */
export function instanceOfSavedProcessRevision(value: object): value is SavedProcessRevision {
    return true;
}

export function SavedProcessRevisionFromJSON(json: any): SavedProcessRevision {
    return SavedProcessRevisionFromJSONTyped(json, false);
}

export function SavedProcessRevisionFromJSONTyped(json: any, ignoreDiscriminator: boolean): SavedProcessRevision {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : ProcessResourceFromJSON(json['type']),
        'uri': json['uri'] == null ? undefined : json['uri'],
        'contentSha256': json['contentSha256'] == null ? undefined : json['contentSha256'],
    };
}

export function SavedProcessRevisionToJSON(json: any): SavedProcessRevision {
    return SavedProcessRevisionToJSONTyped(json, false);
}

export function SavedProcessRevisionToJSONTyped(value?: SavedProcessRevision | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': ProcessResourceToJSON(value['type']),
        'uri': value['uri'],
        'contentSha256': value['contentSha256'],
    };
}

