/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SheetJobType } from './SheetJobType';
import {
    SheetJobTypeFromJSON,
    SheetJobTypeFromJSONTyped,
    SheetJobTypeToJSON,
} from './SheetJobType';
import type { Status } from './Status';
import {
    StatusFromJSON,
    StatusFromJSONTyped,
    StatusToJSON,
} from './Status';

/**
 * 
 * @export
 * @interface SheetJob
 */
export interface SheetJob {
    /**
     * 
     * @type {string}
     * @memberof SheetJob
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof SheetJob
     */
    sheetId: string;
    /**
     * 
     * @type {SheetJobType}
     * @memberof SheetJob
     */
    jobType: SheetJobType;
    /**
     * 
     * @type {Status}
     * @memberof SheetJob
     */
    status: Status;
    /**
     * 
     * @type {Date}
     * @memberof SheetJob
     */
    startedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof SheetJob
     */
    completedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof SheetJob
     */
    failedAtStep?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SheetJob
     */
    errorMessage?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SheetJob
     */
    snapshotId?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof SheetJob
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof SheetJob
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the SheetJob interface.
 */
export function instanceOfSheetJob(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "sheetId" in value;
    isInstance = isInstance && "jobType" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "updatedAt" in value;

    return isInstance;
}

export function SheetJobFromJSON(json: any): SheetJob {
    return SheetJobFromJSONTyped(json, false);
}

export function SheetJobFromJSONTyped(json: any, ignoreDiscriminator: boolean): SheetJob {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'sheetId': json['sheetId'],
        'jobType': SheetJobTypeFromJSON(json['jobType']),
        'status': StatusFromJSON(json['status']),
        'startedAt': !exists(json, 'startedAt') ? undefined : (json['startedAt'] === null ? null : new Date(json['startedAt'])),
        'completedAt': !exists(json, 'completedAt') ? undefined : (json['completedAt'] === null ? null : new Date(json['completedAt'])),
        'failedAtStep': !exists(json, 'failedAtStep') ? undefined : json['failedAtStep'],
        'errorMessage': !exists(json, 'errorMessage') ? undefined : json['errorMessage'],
        'snapshotId': !exists(json, 'snapshotId') ? undefined : json['snapshotId'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function SheetJobToJSON(value?: SheetJob | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'sheetId': value.sheetId,
        'jobType': SheetJobTypeToJSON(value.jobType),
        'status': StatusToJSON(value.status),
        'startedAt': value.startedAt === undefined ? undefined : (value.startedAt === null ? null : value.startedAt.toISOString()),
        'completedAt': value.completedAt === undefined ? undefined : (value.completedAt === null ? null : value.completedAt.toISOString()),
        'failedAtStep': value.failedAtStep,
        'errorMessage': value.errorMessage,
        'snapshotId': value.snapshotId,
        'createdAt': (value.createdAt.toISOString()),
        'updatedAt': (value.updatedAt.toISOString()),
    };
}

