/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SheetDataRequestFilter } from './SheetDataRequestFilter';
import {
    SheetDataRequestFilterFromJSON,
    SheetDataRequestFilterFromJSONTyped,
    SheetDataRequestFilterToJSON,
} from './SheetDataRequestFilter';
import type { SheetDataRequestSort } from './SheetDataRequestSort';
import {
    SheetDataRequestSortFromJSON,
    SheetDataRequestSortFromJSONTyped,
    SheetDataRequestSortToJSON,
} from './SheetDataRequestSort';

/**
 * Paginated sheet data query with optional sort and filter
 * @export
 * @interface SheetDataRequest
 */
export interface SheetDataRequest {
    /**
     * Maximum rows to return
     * @type {number}
     * @memberof SheetDataRequest
     */
    limit?: number | null;
    /**
     * Page to return
     * @type {number}
     * @memberof SheetDataRequest
     */
    page?: number | null;
    /**
     * 
     * @type {SheetDataRequestSort}
     * @memberof SheetDataRequest
     */
    sort?: SheetDataRequestSort | null;
    /**
     * 
     * @type {SheetDataRequestFilter}
     * @memberof SheetDataRequest
     */
    filter?: SheetDataRequestFilter | null;
}

/**
 * Check if a given object implements the SheetDataRequest interface.
 */
export function instanceOfSheetDataRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SheetDataRequestFromJSON(json: any): SheetDataRequest {
    return SheetDataRequestFromJSONTyped(json, false);
}

export function SheetDataRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SheetDataRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'limit': !exists(json, 'limit') ? undefined : json['limit'],
        'page': !exists(json, 'page') ? undefined : json['page'],
        'sort': !exists(json, 'sort') ? undefined : SheetDataRequestSortFromJSON(json['sort']),
        'filter': !exists(json, 'filter') ? undefined : SheetDataRequestFilterFromJSON(json['filter']),
    };
}

export function SheetDataRequestToJSON(value?: SheetDataRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'limit': value.limit,
        'page': value.page,
        'sort': SheetDataRequestSortToJSON(value.sort),
        'filter': SheetDataRequestFilterToJSON(value.filter),
    };
}

