/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SheetTemplate
 */
export interface SheetTemplate {
    /**
     * 
     * @type {Array<string>}
     * @memberof SheetTemplate
     */
    headers: Array<string>;
    /**
     * 
     * @type {Array<Array<string>>}
     * @memberof SheetTemplate
     */
    rows: Array<Array<string>>;
}

/**
 * Check if a given object implements the SheetTemplate interface.
 */
export function instanceOfSheetTemplate(value: object): value is SheetTemplate {
    if (!('headers' in value) || value['headers'] === undefined) return false;
    if (!('rows' in value) || value['rows'] === undefined) return false;
    return true;
}

export function SheetTemplateFromJSON(json: any): SheetTemplate {
    return SheetTemplateFromJSONTyped(json, false);
}

export function SheetTemplateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SheetTemplate {
    if (json == null) {
        return json;
    }
    return {
        
        'headers': json['headers'],
        'rows': json['rows'],
    };
}

export function SheetTemplateToJSON(json: any): SheetTemplate {
    return SheetTemplateToJSONTyped(json, false);
}

export function SheetTemplateToJSONTyped(value?: SheetTemplate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'headers': value['headers'],
        'rows': value['rows'],
    };
}

