/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SheetDetail } from './SheetDetail';
import {
    SheetDetailFromJSON,
    SheetDetailFromJSONTyped,
    SheetDetailToJSON,
    SheetDetailToJSONTyped,
} from './SheetDetail';

/**
 * 
 * @export
 * @interface SheetUpdateResponse
 */
export interface SheetUpdateResponse {
    /**
     * Updated sheet state after the PUT completes. For dry-run, reflects the current (unchanged) state.
     * @type {SheetDetail}
     * @memberof SheetUpdateResponse
     */
    sheet?: SheetDetail;
    /**
     * SQL DDL statements applied (TABLE schema changes) or that WOULD be applied (dryRun). Empty for metadata-only updates and for VIEW updates.
     * @type {Array<string>}
     * @memberof SheetUpdateResponse
     */
    sqlStatements?: Array<string>;
    /**
     * Human-readable summary of the changes applied (or that would be applied for dryRun). Suitable for showing to users unfamiliar with SQL. Empty for metadata-only and VIEW updates.
     * @type {Array<string>}
     * @memberof SheetUpdateResponse
     */
    changes?: Array<string>;
}

/**
 * Check if a given object implements the SheetUpdateResponse interface.
 */
export function instanceOfSheetUpdateResponse(value: object): value is SheetUpdateResponse {
    return true;
}

export function SheetUpdateResponseFromJSON(json: any): SheetUpdateResponse {
    return SheetUpdateResponseFromJSONTyped(json, false);
}

export function SheetUpdateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SheetUpdateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'sheet': json['sheet'] == null ? undefined : SheetDetailFromJSON(json['sheet']),
        'sqlStatements': json['sqlStatements'] == null ? undefined : json['sqlStatements'],
        'changes': json['changes'] == null ? undefined : json['changes'],
    };
}

export function SheetUpdateResponseToJSON(json: any): SheetUpdateResponse {
    return SheetUpdateResponseToJSONTyped(json, false);
}

export function SheetUpdateResponseToJSONTyped(value?: SheetUpdateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sheet': SheetDetailToJSON(value['sheet']),
        'sqlStatements': value['sqlStatements'],
        'changes': value['changes'],
    };
}

