/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum SheetCreationMode {
    File = 'FILE',
    Scratch = 'SCRATCH',
    Template = 'TEMPLATE',
    Standard = 'STANDARD'
}


export function SheetCreationModeFromJSON(json: any): SheetCreationMode {
    return SheetCreationModeFromJSONTyped(json, false);
}

export function SheetCreationModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SheetCreationMode {
    return json as SheetCreationMode;
}

export function SheetCreationModeToJSON(value?: SheetCreationMode | null): any {
    return value as any;
}

