/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ResourcesInfo } from './ResourcesInfo';
import {
    ResourcesInfoFromJSON,
    ResourcesInfoFromJSONTyped,
    ResourcesInfoToJSON,
} from './ResourcesInfo';

/**
 * 
 * @export
 * @interface SystemInfoResponse
 */
export interface SystemInfoResponse {
    /**
     * 
     * @type {string}
     * @memberof SystemInfoResponse
     */
    sdkAppId: string;
    /**
     * 
     * @type {string}
     * @memberof SystemInfoResponse
     */
    resourcesBucket: string;
    /**
     * 
     * @type {string}
     * @memberof SystemInfoResponse
     */
    dataEndpoint: string;
    /**
     * 
     * @type {string}
     * @memberof SystemInfoResponse
     */
    region: string;
    /**
     * 
     * @type {string}
     * @memberof SystemInfoResponse
     */
    systemMessage: string;
    /**
     * 
     * @type {string}
     * @memberof SystemInfoResponse
     */
    commitHash: string;
    /**
     * 
     * @type {string}
     * @memberof SystemInfoResponse
     */
    version: string;
    /**
     * 
     * @type {ResourcesInfo}
     * @memberof SystemInfoResponse
     */
    resourcesInfo: ResourcesInfo;
}

/**
 * Check if a given object implements the SystemInfoResponse interface.
 */
export function instanceOfSystemInfoResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "sdkAppId" in value;
    isInstance = isInstance && "resourcesBucket" in value;
    isInstance = isInstance && "dataEndpoint" in value;
    isInstance = isInstance && "region" in value;
    isInstance = isInstance && "systemMessage" in value;
    isInstance = isInstance && "commitHash" in value;
    isInstance = isInstance && "version" in value;
    isInstance = isInstance && "resourcesInfo" in value;

    return isInstance;
}

export function SystemInfoResponseFromJSON(json: any): SystemInfoResponse {
    return SystemInfoResponseFromJSONTyped(json, false);
}

export function SystemInfoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemInfoResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sdkAppId': json['sdkAppId'],
        'resourcesBucket': json['resourcesBucket'],
        'dataEndpoint': json['dataEndpoint'],
        'region': json['region'],
        'systemMessage': json['systemMessage'],
        'commitHash': json['commitHash'],
        'version': json['version'],
        'resourcesInfo': ResourcesInfoFromJSON(json['resourcesInfo']),
    };
}

export function SystemInfoResponseToJSON(value?: SystemInfoResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sdkAppId': value.sdkAppId,
        'resourcesBucket': value.resourcesBucket,
        'dataEndpoint': value.dataEndpoint,
        'region': value.region,
        'systemMessage': value.systemMessage,
        'commitHash': value.commitHash,
        'version': value.version,
        'resourcesInfo': ResourcesInfoToJSON(value.resourcesInfo),
    };
}

