/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ColumnDef } from './ColumnDef';
import {
    ColumnDefFromJSON,
    ColumnDefFromJSONTyped,
    ColumnDefToJSON,
} from './ColumnDef';
import type { SheetCreationMode } from './SheetCreationMode';
import {
    SheetCreationModeFromJSON,
    SheetCreationModeFromJSONTyped,
    SheetCreationModeToJSON,
} from './SheetCreationMode';

/**
 * 
 * @export
 * @interface TableSheetInput
 */
export interface TableSheetInput {
    /**
     * Display name for the sheet
     * @type {string}
     * @memberof TableSheetInput
     */
    name: string;
    /**
     * Optional description of the sheet's purpose or contents
     * @type {string}
     * @memberof TableSheetInput
     */
    description?: string | null;
    /**
     * Namespace containing the sheet's underlying table. Immutable after create.
     * @type {string}
     * @memberof TableSheetInput
     */
    namespaceName: string;
    /**
     * Name of the sheet's underlying table. Mutable via update.
     * @type {string}
     * @memberof TableSheetInput
     */
    tableName: string;
    /**
     * Enable audit logging for read access to this sheet
     * @type {boolean}
     * @memberof TableSheetInput
     */
    auditReadAccess?: boolean;
    /**
     * 
     * @type {SheetCreationMode}
     * @memberof TableSheetInput
     */
    sheetCreationMode: SheetCreationMode;
    /**
     * Target column list for the sheet. On update, the server computes the diff against existing columns (matched by column id) and applies the resulting ADD/DROP/RENAME/TYPE changes as a single transactional ALTER sequence. Existing columns include their id; new columns omit it.
     * @type {Array<ColumnDef>}
     * @memberof TableSheetInput
     */
    columns: Array<ColumnDef>;
    /**
     * 
     * @type {string}
     * @memberof TableSheetInput
     */
    sheetType?: string;
}

/**
 * Check if a given object implements the TableSheetInput interface.
 */
export function instanceOfTableSheetInput(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "namespaceName" in value;
    isInstance = isInstance && "tableName" in value;
    isInstance = isInstance && "sheetCreationMode" in value;
    isInstance = isInstance && "columns" in value;

    return isInstance;
}

export function TableSheetInputFromJSON(json: any): TableSheetInput {
    return TableSheetInputFromJSONTyped(json, false);
}

export function TableSheetInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): TableSheetInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'namespaceName': json['namespaceName'],
        'tableName': json['tableName'],
        'auditReadAccess': !exists(json, 'auditReadAccess') ? undefined : json['auditReadAccess'],
        'sheetCreationMode': SheetCreationModeFromJSON(json['sheetCreationMode']),
        'columns': ((json['columns'] as Array<any>).map(ColumnDefFromJSON)),
        'sheetType': !exists(json, 'sheetType') ? undefined : json['sheetType'],
    };
}

export function TableSheetInputToJSON(value?: TableSheetInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'namespaceName': value.namespaceName,
        'tableName': value.tableName,
        'auditReadAccess': value.auditReadAccess,
        'sheetCreationMode': SheetCreationModeToJSON(value.sheetCreationMode),
        'columns': ((value.columns as Array<any>).map(ColumnDefToJSON)),
        'sheetType': value.sheetType,
    };
}

