/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Entity } from './Entity';
import {
    EntityFromJSON,
    EntityFromJSONTyped,
    EntityToJSON,
    EntityToJSONTyped,
} from './Entity';
import type { ColumnMapping } from './ColumnMapping';
import {
    ColumnMappingFromJSON,
    ColumnMappingFromJSONTyped,
    ColumnMappingToJSON,
    ColumnMappingToJSONTyped,
} from './ColumnMapping';

/**
 * The saved column mapping from a sheet to one target, such as a pipeline
 * @export
 * @interface TargetMapping
 */
export interface TargetMapping {
    /**
     * 
     * @type {Entity}
     * @memberof TargetMapping
     */
    target: Entity;
    /**
     * 
     * @type {Array<ColumnMapping>}
     * @memberof TargetMapping
     */
    columnMappings: Array<ColumnMapping>;
}

/**
 * Check if a given object implements the TargetMapping interface.
 */
export function instanceOfTargetMapping(value: object): value is TargetMapping {
    if (!('target' in value) || value['target'] === undefined) return false;
    if (!('columnMappings' in value) || value['columnMappings'] === undefined) return false;
    return true;
}

export function TargetMappingFromJSON(json: any): TargetMapping {
    return TargetMappingFromJSONTyped(json, false);
}

export function TargetMappingFromJSONTyped(json: any, ignoreDiscriminator: boolean): TargetMapping {
    if (json == null) {
        return json;
    }
    return {
        
        'target': EntityFromJSON(json['target']),
        'columnMappings': ((json['columnMappings'] as Array<any>).map(ColumnMappingFromJSON)),
    };
}

export function TargetMappingToJSON(json: any): TargetMapping {
    return TargetMappingToJSONTyped(json, false);
}

export function TargetMappingToJSONTyped(value?: TargetMapping | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'target': EntityToJSON(value['target']),
        'columnMappings': ((value['columnMappings'] as Array<any>).map(ColumnMappingToJSON)),
    };
}

