/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskCost
 */
export interface TaskCost {
    /**
     * 
     * @type {string}
     * @memberof TaskCost
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TaskCost
     */
    taskId: string;
    /**
     * 
     * @type {string}
     * @memberof TaskCost
     */
    status: string;
    /**
     * 
     * @type {number}
     * @memberof TaskCost
     */
    cost: number;
}

/**
 * Check if a given object implements the TaskCost interface.
 */
export function instanceOfTaskCost(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "taskId" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "cost" in value;

    return isInstance;
}

export function TaskCostFromJSON(json: any): TaskCost {
    return TaskCostFromJSONTyped(json, false);
}

export function TaskCostFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskCost {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'taskId': json['taskId'],
        'status': json['status'],
        'cost': json['cost'],
    };
}

export function TaskCostToJSON(value?: TaskCost | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'taskId': value.taskId,
        'status': value.status,
        'cost': value.cost,
    };
}

