/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserSettings } from './UserSettings';
import {
    UserSettingsFromJSON,
    UserSettingsFromJSONTyped,
    UserSettingsToJSON,
    UserSettingsToJSONTyped,
} from './UserSettings';
import type { UserProjectAssignment } from './UserProjectAssignment';
import {
    UserProjectAssignmentFromJSON,
    UserProjectAssignmentFromJSONTyped,
    UserProjectAssignmentToJSON,
    UserProjectAssignmentToJSONTyped,
} from './UserProjectAssignment';

/**
 * 
 * @export
 * @interface UserDetail
 */
export interface UserDetail {
    /**
     * 
     * @type {string}
     * @memberof UserDetail
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof UserDetail
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UserDetail
     */
    phone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserDetail
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserDetail
     */
    organization: string;
    /**
     * 
     * @type {string}
     * @memberof UserDetail
     */
    orcidId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserDetail
     */
    jobTitle?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserDetail
     */
    department?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserDetail
     */
    invitedBy?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof UserDetail
     */
    signUpTime?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof UserDetail
     */
    lastSignedIn?: Date | null;
    /**
     * 
     * @type {Array<UserProjectAssignment>}
     * @memberof UserDetail
     */
    projectAssignments: Array<UserProjectAssignment>;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserDetail
     */
    globalRoles: Array<string>;
    /**
     * Replaced by globalRoles.
     * @type {Array<string>}
     * @memberof UserDetail
     * @deprecated
     */
    groups?: Array<string> | null;
    /**
     * 
     * @type {UserSettings}
     * @memberof UserDetail
     */
    settings: UserSettings;
}

/**
 * Check if a given object implements the UserDetail interface.
 */
export function instanceOfUserDetail(value: object): value is UserDetail {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('organization' in value) || value['organization'] === undefined) return false;
    if (!('projectAssignments' in value) || value['projectAssignments'] === undefined) return false;
    if (!('globalRoles' in value) || value['globalRoles'] === undefined) return false;
    if (!('settings' in value) || value['settings'] === undefined) return false;
    return true;
}

export function UserDetailFromJSON(json: any): UserDetail {
    return UserDetailFromJSONTyped(json, false);
}

export function UserDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'name': json['name'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'email': json['email'],
        'organization': json['organization'],
        'orcidId': json['orcidId'] == null ? undefined : json['orcidId'],
        'jobTitle': json['jobTitle'] == null ? undefined : json['jobTitle'],
        'department': json['department'] == null ? undefined : json['department'],
        'invitedBy': json['invitedBy'] == null ? undefined : json['invitedBy'],
        'signUpTime': json['signUpTime'] == null ? undefined : (new Date(json['signUpTime'])),
        'lastSignedIn': json['lastSignedIn'] == null ? undefined : (new Date(json['lastSignedIn'])),
        'projectAssignments': ((json['projectAssignments'] as Array<any>).map(UserProjectAssignmentFromJSON)),
        'globalRoles': json['globalRoles'],
        'groups': json['groups'] == null ? undefined : json['groups'],
        'settings': UserSettingsFromJSON(json['settings']),
    };
}

export function UserDetailToJSON(json: any): UserDetail {
    return UserDetailToJSONTyped(json, false);
}

export function UserDetailToJSONTyped(value?: UserDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'name': value['name'],
        'phone': value['phone'],
        'email': value['email'],
        'organization': value['organization'],
        'orcidId': value['orcidId'],
        'jobTitle': value['jobTitle'],
        'department': value['department'],
        'invitedBy': value['invitedBy'],
        'signUpTime': value['signUpTime'] == null ? value['signUpTime'] : value['signUpTime'].toISOString(),
        'lastSignedIn': value['lastSignedIn'] == null ? value['lastSignedIn'] : value['lastSignedIn'].toISOString(),
        'projectAssignments': ((value['projectAssignments'] as Array<any>).map(UserProjectAssignmentToJSON)),
        'globalRoles': value['globalRoles'],
        'groups': value['groups'],
        'settings': UserSettingsToJSON(value['settings']),
    };
}

