/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VersionInfo
 */
export interface VersionInfo {
    /**
     * 
     * @type {string}
     * @memberof VersionInfo
     */
    commit: string;
    /**
     * 
     * @type {string}
     * @memberof VersionInfo
     */
    version: string;
    /**
     * 
     * @type {Date}
     * @memberof VersionInfo
     */
    date?: Date | null;
}

/**
 * Check if a given object implements the VersionInfo interface.
 */
export function instanceOfVersionInfo(value: object): value is VersionInfo {
    if (!('commit' in value) || value['commit'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function VersionInfoFromJSON(json: any): VersionInfo {
    return VersionInfoFromJSONTyped(json, false);
}

export function VersionInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'commit': json['commit'],
        'version': json['version'],
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
    };
}

export function VersionInfoToJSON(json: any): VersionInfo {
    return VersionInfoToJSONTyped(json, false);
}

export function VersionInfoToJSONTyped(value?: VersionInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'commit': value['commit'],
        'version': value['version'],
        'date': value['date'] == null ? value['date'] : value['date'].toISOString(),
    };
}

