/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VersionSpecification
 */
export interface VersionSpecification {
    /**
     * 
     * @type {string}
     * @memberof VersionSpecification
     */
    version: string;
    /**
     * 
     * @type {boolean}
     * @memberof VersionSpecification
     */
    isDefault: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof VersionSpecification
     */
    isLatest: boolean;
}

/**
 * Check if a given object implements the VersionSpecification interface.
 */
export function instanceOfVersionSpecification(value: object): value is VersionSpecification {
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('isDefault' in value) || value['isDefault'] === undefined) return false;
    if (!('isLatest' in value) || value['isLatest'] === undefined) return false;
    return true;
}

export function VersionSpecificationFromJSON(json: any): VersionSpecification {
    return VersionSpecificationFromJSONTyped(json, false);
}

export function VersionSpecificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionSpecification {
    if (json == null) {
        return json;
    }
    return {
        
        'version': json['version'],
        'isDefault': json['isDefault'],
        'isLatest': json['isLatest'],
    };
}

export function VersionSpecificationToJSON(json: any): VersionSpecification {
    return VersionSpecificationToJSONTyped(json, false);
}

export function VersionSpecificationToJSONTyped(value?: VersionSpecification | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version': value['version'],
        'isDefault': value['isDefault'],
        'isLatest': value['isLatest'],
    };
}

