/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { RawViewQueryRequest } from './RawViewQueryRequest';
import {
    instanceOfRawViewQueryRequest,
    RawViewQueryRequestFromJSON,
    RawViewQueryRequestFromJSONTyped,
    RawViewQueryRequestToJSON,
} from './RawViewQueryRequest';
import type { StructuredViewQueryRequest } from './StructuredViewQueryRequest';
import {
    instanceOfStructuredViewQueryRequest,
    StructuredViewQueryRequestFromJSON,
    StructuredViewQueryRequestFromJSONTyped,
    StructuredViewQueryRequestToJSON,
} from './StructuredViewQueryRequest';

/**
 * @type ViewQueryRequest
 * View definition. viewType=STRUCTURED for standard builder; viewType=RAW for a SQL SELECT.
 * @export
 */
export type ViewQueryRequest = { viewType: 'RAW' } & RawViewQueryRequest | { viewType: 'STRUCTURED' } & StructuredViewQueryRequest;

export function ViewQueryRequestFromJSON(json: any): ViewQueryRequest {
    return ViewQueryRequestFromJSONTyped(json, false);
}

export function ViewQueryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViewQueryRequest {
    if (json == null) {
        return json;
    }
    switch (json['viewType']) {
        case 'RAW':
            return Object.assign({}, RawViewQueryRequestFromJSONTyped(json, true), { viewType: 'RAW' } as const);
        case 'STRUCTURED':
            return Object.assign({}, StructuredViewQueryRequestFromJSONTyped(json, true), { viewType: 'STRUCTURED' } as const);
        default:
            return json;
    }
}

export function ViewQueryRequestToJSON(json: any): any {
    return ViewQueryRequestToJSONTyped(json, false);
}

export function ViewQueryRequestToJSONTyped(value?: ViewQueryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['viewType']) {
        case 'RAW':
            return Object.assign({}, RawViewQueryRequestToJSON(value), { viewType: 'RAW' } as const);
        case 'STRUCTURED':
            return Object.assign({}, StructuredViewQueryRequestToJSON(value), { viewType: 'STRUCTURED' } as const);
        default:
            return value;
    }
}

