/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ViewQueryRequest } from './ViewQueryRequest';
import {
    ViewQueryRequestFromJSON,
    ViewQueryRequestFromJSONTyped,
    ViewQueryRequestToJSON,
} from './ViewQueryRequest';

/**
 * 
 * @export
 * @interface ViewSheetInput
 */
export interface ViewSheetInput {
    /**
     * Display name for the sheet
     * @type {string}
     * @memberof ViewSheetInput
     */
    name: string;
    /**
     * Optional description of the sheet's purpose or contents
     * @type {string}
     * @memberof ViewSheetInput
     */
    description?: string | null;
    /**
     * Namespace containing the sheet's underlying table. Immutable after create.
     * @type {string}
     * @memberof ViewSheetInput
     */
    namespaceName: string;
    /**
     * Name of the sheet's underlying table. Mutable via update.
     * @type {string}
     * @memberof ViewSheetInput
     */
    tableName: string;
    /**
     * Enable audit logging for read access to this sheet
     * @type {boolean}
     * @memberof ViewSheetInput
     */
    auditReadAccess?: boolean;
    /**
     * 
     * @type {ViewQueryRequest}
     * @memberof ViewSheetInput
     */
    viewDefinition: ViewQueryRequest;
    /**
     * 
     * @type {string}
     * @memberof ViewSheetInput
     */
    sheetType?: string;
}

/**
 * Check if a given object implements the ViewSheetInput interface.
 */
export function instanceOfViewSheetInput(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "namespaceName" in value;
    isInstance = isInstance && "tableName" in value;
    isInstance = isInstance && "viewDefinition" in value;

    return isInstance;
}

export function ViewSheetInputFromJSON(json: any): ViewSheetInput {
    return ViewSheetInputFromJSONTyped(json, false);
}

export function ViewSheetInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViewSheetInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'namespaceName': json['namespaceName'],
        'tableName': json['tableName'],
        'auditReadAccess': !exists(json, 'auditReadAccess') ? undefined : json['auditReadAccess'],
        'viewDefinition': ViewQueryRequestFromJSON(json['viewDefinition']),
        'sheetType': !exists(json, 'sheetType') ? undefined : json['sheetType'],
    };
}

export function ViewSheetInputToJSON(value?: ViewSheetInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'namespaceName': value.namespaceName,
        'tableName': value.tableName,
        'auditReadAccess': value.auditReadAccess,
        'viewDefinition': ViewQueryRequestToJSON(value.viewDefinition),
        'sheetType': value.sheetType,
    };
}

