/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkspaceConnectionResponse
 */
export interface WorkspaceConnectionResponse {
    /**
     * 
     * @type {string}
     * @memberof WorkspaceConnectionResponse
     */
    connectionUrl: string;
    /**
     * 
     * @type {Date}
     * @memberof WorkspaceConnectionResponse
     */
    expiresAt: Date;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceConnectionResponse
     */
    message: string;
}

/**
 * Check if a given object implements the WorkspaceConnectionResponse interface.
 */
export function instanceOfWorkspaceConnectionResponse(value: object): value is WorkspaceConnectionResponse {
    if (!('connectionUrl' in value) || value['connectionUrl'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function WorkspaceConnectionResponseFromJSON(json: any): WorkspaceConnectionResponse {
    return WorkspaceConnectionResponseFromJSONTyped(json, false);
}

export function WorkspaceConnectionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkspaceConnectionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'connectionUrl': json['connectionUrl'],
        'expiresAt': (new Date(json['expiresAt'])),
        'message': json['message'],
    };
}

export function WorkspaceConnectionResponseToJSON(json: any): WorkspaceConnectionResponse {
    return WorkspaceConnectionResponseToJSONTyped(json, false);
}

export function WorkspaceConnectionResponseToJSONTyped(value?: WorkspaceConnectionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'connectionUrl': value['connectionUrl'],
        'expiresAt': value['expiresAt'].toISOString(),
        'message': value['message'],
    };
}

