/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AppRegistration,
  AppRegistrationDetail,
  AppRegistrationInput,
  AppRegistrationSecretResponse,
  PaginatedResponseAppRegistrationDto,
} from '../models/index';
import {
    AppRegistrationFromJSON,
    AppRegistrationToJSON,
    AppRegistrationDetailFromJSON,
    AppRegistrationDetailToJSON,
    AppRegistrationInputFromJSON,
    AppRegistrationInputToJSON,
    AppRegistrationSecretResponseFromJSON,
    AppRegistrationSecretResponseToJSON,
    PaginatedResponseAppRegistrationDtoFromJSON,
    PaginatedResponseAppRegistrationDtoToJSON,
} from '../models/index';

export interface ArchiveAppRegistrationRequest {
    id: string;
}

export interface CreateAppRegistrationRequest {
    appRegistrationInput: AppRegistrationInput;
}

export interface GetAppRegistrationRequest {
    id: string;
}

export interface ListAppRegistrationsRequest {
    limit: number;
    nextToken: string;
}

export interface RegenerateSecretRequest {
    id: string;
}

export interface UpdateAppRegistrationRequest {
    id: string;
    appRegistrationInput: AppRegistrationInput;
}

/**
 * 
 */
export class AppRegistrationsApi extends runtime.BaseAPI {

    /**
     * Archives an app registration. Archived registrations cannot authenticate.
     * Archive app registration
     */
    async archiveAppRegistrationRaw(requestParameters: ArchiveAppRegistrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling archiveAppRegistration.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/app-registrations/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Archives an app registration. Archived registrations cannot authenticate.
     * Archive app registration
     */
    async archiveAppRegistration(requestParameters: ArchiveAppRegistrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.archiveAppRegistrationRaw(requestParameters, initOverrides);
    }

    /**
     * Creates a new OAuth client app registration. Returns the client secret which is only shown once.
     * Create app registration
     */
    async createAppRegistrationRaw(requestParameters: CreateAppRegistrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppRegistrationSecretResponse>> {
        if (requestParameters.appRegistrationInput === null || requestParameters.appRegistrationInput === undefined) {
            throw new runtime.RequiredError('appRegistrationInput','Required parameter requestParameters.appRegistrationInput was null or undefined when calling createAppRegistration.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/app-registrations`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AppRegistrationInputToJSON(requestParameters.appRegistrationInput),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppRegistrationSecretResponseFromJSON(jsonValue));
    }

    /**
     * Creates a new OAuth client app registration. Returns the client secret which is only shown once.
     * Create app registration
     */
    async createAppRegistration(requestParameters: CreateAppRegistrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppRegistrationSecretResponse> {
        const response = await this.createAppRegistrationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Gets detailed information about an app registration.
     * Get app registration
     */
    async getAppRegistrationRaw(requestParameters: GetAppRegistrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppRegistrationDetail>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling getAppRegistration.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/app-registrations/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppRegistrationDetailFromJSON(jsonValue));
    }

    /**
     * Gets detailed information about an app registration.
     * Get app registration
     */
    async getAppRegistration(requestParameters: GetAppRegistrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppRegistrationDetail> {
        const response = await this.getAppRegistrationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Lists all app registrations in the system.
     * List app registrations
     */
    async listAppRegistrationsRaw(requestParameters: ListAppRegistrationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedResponseAppRegistrationDto>> {
        if (requestParameters.limit === null || requestParameters.limit === undefined) {
            throw new runtime.RequiredError('limit','Required parameter requestParameters.limit was null or undefined when calling listAppRegistrations.');
        }

        if (requestParameters.nextToken === null || requestParameters.nextToken === undefined) {
            throw new runtime.RequiredError('nextToken','Required parameter requestParameters.nextToken was null or undefined when calling listAppRegistrations.');
        }

        const queryParameters: any = {};

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.nextToken !== undefined) {
            queryParameters['nextToken'] = requestParameters.nextToken;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/app-registrations`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedResponseAppRegistrationDtoFromJSON(jsonValue));
    }

    /**
     * Lists all app registrations in the system.
     * List app registrations
     */
    async listAppRegistrations(requestParameters: ListAppRegistrationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedResponseAppRegistrationDto> {
        const response = await this.listAppRegistrationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Lists app registrations created by the current user.
     * List my app registrations
     */
    async listMyAppRegistrationsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AppRegistration>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/app-registrations/mine`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AppRegistrationFromJSON));
    }

    /**
     * Lists app registrations created by the current user.
     * List my app registrations
     */
    async listMyAppRegistrations(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AppRegistration>> {
        const response = await this.listMyAppRegistrationsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Generates a new client secret for the app registration. The old secret is invalidated.
     * Regenerate client secret
     */
    async regenerateSecretRaw(requestParameters: RegenerateSecretRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppRegistrationSecretResponse>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling regenerateSecret.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/app-registrations/{id}:regenerate-secret`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppRegistrationSecretResponseFromJSON(jsonValue));
    }

    /**
     * Generates a new client secret for the app registration. The old secret is invalidated.
     * Regenerate client secret
     */
    async regenerateSecret(requestParameters: RegenerateSecretRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppRegistrationSecretResponse> {
        const response = await this.regenerateSecretRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates an existing app registration.
     * Update app registration
     */
    async updateAppRegistrationRaw(requestParameters: UpdateAppRegistrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppRegistrationDetail>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling updateAppRegistration.');
        }

        if (requestParameters.appRegistrationInput === null || requestParameters.appRegistrationInput === undefined) {
            throw new runtime.RequiredError('appRegistrationInput','Required parameter requestParameters.appRegistrationInput was null or undefined when calling updateAppRegistration.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/app-registrations/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: AppRegistrationInputToJSON(requestParameters.appRegistrationInput),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppRegistrationDetailFromJSON(jsonValue));
    }

    /**
     * Updates an existing app registration.
     * Update app registration
     */
    async updateAppRegistration(requestParameters: UpdateAppRegistrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppRegistrationDetail> {
        const response = await this.updateAppRegistrationRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
