/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CostResponse,
    CostResponseFromJSON,
    CostResponseToJSON,
} from '../models/CostResponse';
import {
    type CreateResponse,
    CreateResponseFromJSON,
    CreateResponseToJSON,
} from '../models/CreateResponse';
import {
    type GetExecutionLogsResponse,
    GetExecutionLogsResponseFromJSON,
    GetExecutionLogsResponseToJSON,
} from '../models/GetExecutionLogsResponse';
import {
    type RunAnalysisRequest,
    RunAnalysisRequestFromJSON,
    RunAnalysisRequestToJSON,
} from '../models/RunAnalysisRequest';
import {
    type StopExecutionResponse,
    StopExecutionResponseFromJSON,
    StopExecutionResponseToJSON,
} from '../models/StopExecutionResponse';
import {
    type Task,
    TaskFromJSON,
    TaskToJSON,
} from '../models/Task';

export interface CalculateCostRequest {
    projectId: string;
    datasetId: string;
}

export interface GetExecutionLogsRequest {
    datasetId: string;
    projectId: string;
    forceLive?: boolean;
}

export interface GetProjectSummaryRequest {
    projectId: string;
    numberOfDays?: number;
}

export interface GetTaskRequest {
    datasetId: string;
    projectId: string;
    taskId: string;
    forceLive?: boolean;
}

export interface GetTaskLogsRequest {
    datasetId: string;
    projectId: string;
    taskId: string;
    forceLive?: boolean;
}

export interface GetTasksForExecutionRequest {
    datasetId: string;
    projectId: string;
    forceLive?: boolean;
}

export interface RunAnalysisOperationRequest {
    projectId: string;
    runAnalysisRequest: RunAnalysisRequest;
}

export interface StopAnalysisRequest {
    datasetId: string;
    projectId: string;
}

/**
 * 
 */
export class ExecutionApi extends runtime.BaseAPI {

    /**
     * Creates request options for calculateCost without sending the request
     */
    async calculateCostRequestOpts(requestParameters: CalculateCostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling calculateCost().'
            );
        }

        if (requestParameters['datasetId'] == null) {
            throw new runtime.RequiredError(
                'datasetId',
                'Required parameter "datasetId" was null or undefined when calling calculateCost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects/{projectId}/execution/{datasetId}/cost`;
        urlPath = urlPath.replace('{projectId}', encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace('{datasetId}', encodeURIComponent(String(requestParameters['datasetId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Calculate cost of an execution run
     * Calculate cost
     */
    async calculateCostRaw(requestParameters: CalculateCostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CostResponse>> {
        const requestOptions = await this.calculateCostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CostResponseFromJSON(jsonValue));
    }

    /**
     * Calculate cost of an execution run
     * Calculate cost
     */
    async calculateCost(requestParameters: CalculateCostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CostResponse> {
        const response = await this.calculateCostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getExecutionLogs without sending the request
     */
    async getExecutionLogsRequestOpts(requestParameters: GetExecutionLogsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['datasetId'] == null) {
            throw new runtime.RequiredError(
                'datasetId',
                'Required parameter "datasetId" was null or undefined when calling getExecutionLogs().'
            );
        }

        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getExecutionLogs().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['forceLive'] != null) {
            queryParameters['forceLive'] = requestParameters['forceLive'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects/{projectId}/execution/{datasetId}/logs`;
        urlPath = urlPath.replace('{datasetId}', encodeURIComponent(String(requestParameters['datasetId'])));
        urlPath = urlPath.replace('{projectId}', encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Gets live logs from main execution task
     * Get execution logs
     */
    async getExecutionLogsRaw(requestParameters: GetExecutionLogsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetExecutionLogsResponse>> {
        const requestOptions = await this.getExecutionLogsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetExecutionLogsResponseFromJSON(jsonValue));
    }

    /**
     * Gets live logs from main execution task
     * Get execution logs
     */
    async getExecutionLogs(requestParameters: GetExecutionLogsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetExecutionLogsResponse> {
        const response = await this.getExecutionLogsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getProjectSummary without sending the request
     */
    async getProjectSummaryRequestOpts(requestParameters: GetProjectSummaryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getProjectSummary().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['numberOfDays'] != null) {
            queryParameters['numberOfDays'] = requestParameters['numberOfDays'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects/{projectId}/execution`;
        urlPath = urlPath.replace('{projectId}', encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Gets an overview of the executions currently running in the project
     * Get execution summary
     */
    async getProjectSummaryRaw(requestParameters: GetProjectSummaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: Array<Task>; }>> {
        const requestOptions = await this.getProjectSummaryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Gets an overview of the executions currently running in the project
     * Get execution summary
     */
    async getProjectSummary(requestParameters: GetProjectSummaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: Array<Task>; }> {
        const response = await this.getProjectSummaryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTask without sending the request
     */
    async getTaskRequestOpts(requestParameters: GetTaskRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['datasetId'] == null) {
            throw new runtime.RequiredError(
                'datasetId',
                'Required parameter "datasetId" was null or undefined when calling getTask().'
            );
        }

        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getTask().'
            );
        }

        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling getTask().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['forceLive'] != null) {
            queryParameters['forceLive'] = requestParameters['forceLive'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects/{projectId}/execution/{datasetId}/tasks/{taskId}`;
        urlPath = urlPath.replace('{datasetId}', encodeURIComponent(String(requestParameters['datasetId'])));
        urlPath = urlPath.replace('{projectId}', encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace('{taskId}', encodeURIComponent(String(requestParameters['taskId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Gets detailed information on the individual task
     * Get task
     */
    async getTaskRaw(requestParameters: GetTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Task>> {
        const requestOptions = await this.getTaskRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskFromJSON(jsonValue));
    }

    /**
     * Gets detailed information on the individual task
     * Get task
     */
    async getTask(requestParameters: GetTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Task> {
        const response = await this.getTaskRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTaskLogs without sending the request
     */
    async getTaskLogsRequestOpts(requestParameters: GetTaskLogsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['datasetId'] == null) {
            throw new runtime.RequiredError(
                'datasetId',
                'Required parameter "datasetId" was null or undefined when calling getTaskLogs().'
            );
        }

        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getTaskLogs().'
            );
        }

        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling getTaskLogs().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['forceLive'] != null) {
            queryParameters['forceLive'] = requestParameters['forceLive'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects/{projectId}/execution/{datasetId}/tasks/{taskId}/logs`;
        urlPath = urlPath.replace('{datasetId}', encodeURIComponent(String(requestParameters['datasetId'])));
        urlPath = urlPath.replace('{projectId}', encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace('{taskId}', encodeURIComponent(String(requestParameters['taskId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Gets the log output from an individual task
     * Get task logs
     */
    async getTaskLogsRaw(requestParameters: GetTaskLogsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetExecutionLogsResponse>> {
        const requestOptions = await this.getTaskLogsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetExecutionLogsResponseFromJSON(jsonValue));
    }

    /**
     * Gets the log output from an individual task
     * Get task logs
     */
    async getTaskLogs(requestParameters: GetTaskLogsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetExecutionLogsResponse> {
        const response = await this.getTaskLogsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTasksForExecution without sending the request
     */
    async getTasksForExecutionRequestOpts(requestParameters: GetTasksForExecutionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['datasetId'] == null) {
            throw new runtime.RequiredError(
                'datasetId',
                'Required parameter "datasetId" was null or undefined when calling getTasksForExecution().'
            );
        }

        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getTasksForExecution().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['forceLive'] != null) {
            queryParameters['forceLive'] = requestParameters['forceLive'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects/{projectId}/execution/{datasetId}/tasks`;
        urlPath = urlPath.replace('{datasetId}', encodeURIComponent(String(requestParameters['datasetId'])));
        urlPath = urlPath.replace('{projectId}', encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Gets the tasks submitted by the workflow execution
     * Get execution tasks
     */
    async getTasksForExecutionRaw(requestParameters: GetTasksForExecutionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Task>>> {
        const requestOptions = await this.getTasksForExecutionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TaskFromJSON));
    }

    /**
     * Gets the tasks submitted by the workflow execution
     * Get execution tasks
     */
    async getTasksForExecution(requestParameters: GetTasksForExecutionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Task>> {
        const response = await this.getTasksForExecutionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for runAnalysis without sending the request
     */
    async runAnalysisRequestOpts(requestParameters: RunAnalysisOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling runAnalysis().'
            );
        }

        if (requestParameters['runAnalysisRequest'] == null) {
            throw new runtime.RequiredError(
                'runAnalysisRequest',
                'Required parameter "runAnalysisRequest" was null or undefined when calling runAnalysis().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects/{projectId}/execution`;
        urlPath = urlPath.replace('{projectId}', encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RunAnalysisRequestToJSON(requestParameters['runAnalysisRequest']),
        };
    }

    /**
     * Run analysis
     * Run analysis
     */
    async runAnalysisRaw(requestParameters: RunAnalysisOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateResponse>> {
        const requestOptions = await this.runAnalysisRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateResponseFromJSON(jsonValue));
    }

    /**
     * Run analysis
     * Run analysis
     */
    async runAnalysis(requestParameters: RunAnalysisOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateResponse> {
        const response = await this.runAnalysisRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for stopAnalysis without sending the request
     */
    async stopAnalysisRequestOpts(requestParameters: StopAnalysisRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['datasetId'] == null) {
            throw new runtime.RequiredError(
                'datasetId',
                'Required parameter "datasetId" was null or undefined when calling stopAnalysis().'
            );
        }

        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling stopAnalysis().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects/{projectId}/execution/{datasetId}/stop`;
        urlPath = urlPath.replace('{datasetId}', encodeURIComponent(String(requestParameters['datasetId'])));
        urlPath = urlPath.replace('{projectId}', encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Terminates all analysis jobs related to this execution
     * Stop execution
     */
    async stopAnalysisRaw(requestParameters: StopAnalysisRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StopExecutionResponse>> {
        const requestOptions = await this.stopAnalysisRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StopExecutionResponseFromJSON(jsonValue));
    }

    /**
     * Terminates all analysis jobs related to this execution
     * Stop execution
     */
    async stopAnalysis(requestParameters: StopAnalysisRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StopExecutionResponse> {
        const response = await this.stopAnalysisRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
