/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type FormSchema,
    FormSchemaFromJSON,
    FormSchemaToJSON,
} from '../models/FormSchema';
import {
    type PaginatedResponseSampleDto,
    PaginatedResponseSampleDtoFromJSON,
    PaginatedResponseSampleDtoToJSON,
} from '../models/PaginatedResponseSampleDto';
import {
    type Sample,
    SampleFromJSON,
    SampleToJSON,
} from '../models/Sample';
import {
    type SampleRequest,
    SampleRequestFromJSON,
    SampleRequestToJSON,
} from '../models/SampleRequest';

export interface GetDatasetSamplesRequest {
    projectId: string;
    datasetId: string;
}

export interface GetProjectSamplesRequest {
    projectId: string;
    limit?: number;
    nextToken?: string;
}

export interface GetProjectSchemaRequest {
    projectId: string;
}

export interface GetSampleByIdRequest {
    projectId: string;
    sampleId: string;
}

export interface UpdateProjectSchemaRequest {
    projectId: string;
    formSchema: FormSchema;
}

export interface UpdateSampleRequest {
    projectId: string;
    sampleId: string;
    sampleRequest: SampleRequest;
}

/**
 * 
 */
export class MetadataApi extends runtime.BaseAPI {

    /**
     * Creates request options for getDatasetSamples without sending the request
     */
    async getDatasetSamplesRequestOpts(requestParameters: GetDatasetSamplesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getDatasetSamples().'
            );
        }

        if (requestParameters['datasetId'] == null) {
            throw new runtime.RequiredError(
                'datasetId',
                'Required parameter "datasetId" was null or undefined when calling getDatasetSamples().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects/{projectId}/datasets/{datasetId}/samples`;
        urlPath = urlPath.replace('{projectId}', encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace('{datasetId}', encodeURIComponent(String(requestParameters['datasetId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves a list of samples associated with a dataset along with their metadata
     * Get dataset samples
     */
    async getDatasetSamplesRaw(requestParameters: GetDatasetSamplesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Sample>>> {
        const requestOptions = await this.getDatasetSamplesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SampleFromJSON));
    }

    /**
     * Retrieves a list of samples associated with a dataset along with their metadata
     * Get dataset samples
     */
    async getDatasetSamples(requestParameters: GetDatasetSamplesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Sample>> {
        const response = await this.getDatasetSamplesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getProjectSamples without sending the request
     */
    async getProjectSamplesRequestOpts(requestParameters: GetProjectSamplesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getProjectSamples().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['nextToken'] != null) {
            queryParameters['nextToken'] = requestParameters['nextToken'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects/{projectId}/samples`;
        urlPath = urlPath.replace('{projectId}', encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves a list of samples associated with a project along with their metadata
     * Get project samples
     */
    async getProjectSamplesRaw(requestParameters: GetProjectSamplesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedResponseSampleDto>> {
        const requestOptions = await this.getProjectSamplesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedResponseSampleDtoFromJSON(jsonValue));
    }

    /**
     * Retrieves a list of samples associated with a project along with their metadata
     * Get project samples
     */
    async getProjectSamples(requestParameters: GetProjectSamplesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedResponseSampleDto> {
        const response = await this.getProjectSamplesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getProjectSchema without sending the request
     */
    async getProjectSchemaRequestOpts(requestParameters: GetProjectSchemaRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getProjectSchema().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects/{projectId}/schema`;
        urlPath = urlPath.replace('{projectId}', encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get project metadata schema
     */
    async getProjectSchemaRaw(requestParameters: GetProjectSchemaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FormSchema>> {
        const requestOptions = await this.getProjectSchemaRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FormSchemaFromJSON(jsonValue));
    }

    /**
     * Get project metadata schema
     */
    async getProjectSchema(requestParameters: GetProjectSchemaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FormSchema> {
        const response = await this.getProjectSchemaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSampleById without sending the request
     */
    async getSampleByIdRequestOpts(requestParameters: GetSampleByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getSampleById().'
            );
        }

        if (requestParameters['sampleId'] == null) {
            throw new runtime.RequiredError(
                'sampleId',
                'Required parameter "sampleId" was null or undefined when calling getSampleById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects/{projectId}/samples/{sampleId}`;
        urlPath = urlPath.replace('{projectId}', encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace('{sampleId}', encodeURIComponent(String(requestParameters['sampleId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves a sample by its ID along with its metadata
     * Get sample by ID
     */
    async getSampleByIdRaw(requestParameters: GetSampleByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Sample>> {
        const requestOptions = await this.getSampleByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SampleFromJSON(jsonValue));
    }

    /**
     * Retrieves a sample by its ID along with its metadata
     * Get sample by ID
     */
    async getSampleById(requestParameters: GetSampleByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Sample> {
        const response = await this.getSampleByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateProjectSchema without sending the request
     */
    async updateProjectSchemaRequestOpts(requestParameters: UpdateProjectSchemaRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling updateProjectSchema().'
            );
        }

        if (requestParameters['formSchema'] == null) {
            throw new runtime.RequiredError(
                'formSchema',
                'Required parameter "formSchema" was null or undefined when calling updateProjectSchema().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects/{projectId}/schema`;
        urlPath = urlPath.replace('{projectId}', encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: FormSchemaToJSON(requestParameters['formSchema']),
        };
    }

    /**
     * Update project metadata schema
     */
    async updateProjectSchemaRaw(requestParameters: UpdateProjectSchemaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.updateProjectSchemaRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update project metadata schema
     */
    async updateProjectSchema(requestParameters: UpdateProjectSchemaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateProjectSchemaRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for updateSample without sending the request
     */
    async updateSampleRequestOpts(requestParameters: UpdateSampleRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling updateSample().'
            );
        }

        if (requestParameters['sampleId'] == null) {
            throw new runtime.RequiredError(
                'sampleId',
                'Required parameter "sampleId" was null or undefined when calling updateSample().'
            );
        }

        if (requestParameters['sampleRequest'] == null) {
            throw new runtime.RequiredError(
                'sampleRequest',
                'Required parameter "sampleRequest" was null or undefined when calling updateSample().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects/{projectId}/samples/{sampleId}`;
        urlPath = urlPath.replace('{projectId}', encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace('{sampleId}', encodeURIComponent(String(requestParameters['sampleId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SampleRequestToJSON(requestParameters['sampleRequest']),
        };
    }

    /**
     * Updates metadata on a sample
     * Update sample
     */
    async updateSampleRaw(requestParameters: UpdateSampleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Sample>> {
        const requestOptions = await this.updateSampleRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SampleFromJSON(jsonValue));
    }

    /**
     * Updates metadata on a sample
     * Update sample
     */
    async updateSample(requestParameters: UpdateSampleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Sample> {
        const response = await this.updateSampleRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
