/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ApproveProjectAccessRequest,
    ApproveProjectAccessRequestFromJSON,
    ApproveProjectAccessRequestToJSON,
} from '../models/ApproveProjectAccessRequest';
import {
    type CloudQuota,
    CloudQuotaFromJSON,
    CloudQuotaToJSON,
} from '../models/CloudQuota';
import {
    type CreateProjectAccessRequest,
    CreateProjectAccessRequestFromJSON,
    CreateProjectAccessRequestToJSON,
} from '../models/CreateProjectAccessRequest';
import {
    type CreateResponse,
    CreateResponseFromJSON,
    CreateResponseToJSON,
} from '../models/CreateResponse';
import {
    type Project,
    ProjectFromJSON,
    ProjectToJSON,
} from '../models/Project';
import {
    type ProjectAccessRequest,
    ProjectAccessRequestFromJSON,
    ProjectAccessRequestToJSON,
} from '../models/ProjectAccessRequest';
import {
    type ProjectCreateOptions,
    ProjectCreateOptionsFromJSON,
    ProjectCreateOptionsToJSON,
} from '../models/ProjectCreateOptions';
import {
    type ProjectDetail,
    ProjectDetailFromJSON,
    ProjectDetailToJSON,
} from '../models/ProjectDetail';
import {
    type ProjectInput,
    ProjectInputFromJSON,
    ProjectInputToJSON,
} from '../models/ProjectInput';
import {
    type ProjectUser,
    ProjectUserFromJSON,
    ProjectUserToJSON,
} from '../models/ProjectUser';
import {
    type RequestQuotaIncreaseCommand,
    RequestQuotaIncreaseCommandFromJSON,
    RequestQuotaIncreaseCommandToJSON,
} from '../models/RequestQuotaIncreaseCommand';
import {
    type RequestQuotaIncreaseResponse,
    RequestQuotaIncreaseResponseFromJSON,
    RequestQuotaIncreaseResponseToJSON,
} from '../models/RequestQuotaIncreaseResponse';
import {
    type SetUserProjectRoleRequest,
    SetUserProjectRoleRequestFromJSON,
    SetUserProjectRoleRequestToJSON,
} from '../models/SetUserProjectRoleRequest';
import {
    type Tag,
    TagFromJSON,
    TagToJSON,
} from '../models/Tag';

export interface ApproveAccessRequestRequest {
    projectId: string;
    accessRequestId: string;
    approveProjectAccessRequest: ApproveProjectAccessRequest;
}

export interface ArchiveProjectRequest {
    projectId: string;
}

export interface CreateAccessRequestRequest {
    projectId: string;
    createProjectAccessRequest: CreateProjectAccessRequest;
}

export interface CreateProjectRequest {
    projectInput: ProjectInput;
}

export interface DenyAccessRequestRequest {
    projectId: string;
    accessRequestId: string;
}

export interface GetAccessRequestsRequest {
    projectId: string;
    includeClosed?: boolean;
}

export interface GetProjectRequest {
    projectId: string;
}

export interface GetProjectUsersRequest {
    projectId: string;
}

export interface GetQuotasRequest {
    projectId: string;
}

export interface RedeployProjectRequest {
    projectId: string;
}

export interface RequestQuotaIncreaseRequest {
    projectId: string;
    requestQuotaIncreaseCommand: RequestQuotaIncreaseCommand;
}

export interface SetUserProjectRoleOperationRequest {
    projectId: string;
    setUserProjectRoleRequest: SetUserProjectRoleRequest;
}

export interface UnarchiveProjectRequest {
    projectId: string;
}

export interface UpdateProjectRequest {
    projectId: string;
    projectInput: ProjectInput;
}

export interface UpdateProjectTagsRequest {
    projectId: string;
    tag: Array<Tag>;
}

/**
 * 
 */
export class ProjectsApi extends runtime.BaseAPI {

    /**
     * Creates request options for approveAccessRequest without sending the request
     */
    async approveAccessRequestRequestOpts(requestParameters: ApproveAccessRequestRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling approveAccessRequest().'
            );
        }

        if (requestParameters['accessRequestId'] == null) {
            throw new runtime.RequiredError(
                'accessRequestId',
                'Required parameter "accessRequestId" was null or undefined when calling approveAccessRequest().'
            );
        }

        if (requestParameters['approveProjectAccessRequest'] == null) {
            throw new runtime.RequiredError(
                'approveProjectAccessRequest',
                'Required parameter "approveProjectAccessRequest" was null or undefined when calling approveAccessRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects/{projectId}/access-requests/{accessRequestId}:approve`;
        urlPath = urlPath.replace('{projectId}', encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace('{accessRequestId}', encodeURIComponent(String(requestParameters['accessRequestId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ApproveProjectAccessRequestToJSON(requestParameters['approveProjectAccessRequest']),
        };
    }

    /**
     * Approves an access request for the project
     * Approve access request
     */
    async approveAccessRequestRaw(requestParameters: ApproveAccessRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.approveAccessRequestRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Approves an access request for the project
     * Approve access request
     */
    async approveAccessRequest(requestParameters: ApproveAccessRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.approveAccessRequestRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for archiveProject without sending the request
     */
    async archiveProjectRequestOpts(requestParameters: ArchiveProjectRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling archiveProject().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects/{projectId}:archive`;
        urlPath = urlPath.replace('{projectId}', encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Sets the project status to archived
     * Archive project
     */
    async archiveProjectRaw(requestParameters: ArchiveProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.archiveProjectRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Sets the project status to archived
     * Archive project
     */
    async archiveProject(requestParameters: ArchiveProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.archiveProjectRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for createAccessRequest without sending the request
     */
    async createAccessRequestRequestOpts(requestParameters: CreateAccessRequestRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling createAccessRequest().'
            );
        }

        if (requestParameters['createProjectAccessRequest'] == null) {
            throw new runtime.RequiredError(
                'createProjectAccessRequest',
                'Required parameter "createProjectAccessRequest" was null or undefined when calling createAccessRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects/{projectId}/access-requests`;
        urlPath = urlPath.replace('{projectId}', encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateProjectAccessRequestToJSON(requestParameters['createProjectAccessRequest']),
        };
    }

    /**
     * Creates an access request for the project
     * Create access request
     */
    async createAccessRequestRaw(requestParameters: CreateAccessRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateResponse>> {
        const requestOptions = await this.createAccessRequestRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateResponseFromJSON(jsonValue));
    }

    /**
     * Creates an access request for the project
     * Create access request
     */
    async createAccessRequest(requestParameters: CreateAccessRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateResponse> {
        const response = await this.createAccessRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createProject without sending the request
     */
    async createProjectRequestOpts(requestParameters: CreateProjectRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectInput'] == null) {
            throw new runtime.RequiredError(
                'projectInput',
                'Required parameter "projectInput" was null or undefined when calling createProject().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProjectInputToJSON(requestParameters['projectInput']),
        };
    }

    /**
     * Creates a project
     * Create project
     */
    async createProjectRaw(requestParameters: CreateProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateResponse>> {
        const requestOptions = await this.createProjectRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateResponseFromJSON(jsonValue));
    }

    /**
     * Creates a project
     * Create project
     */
    async createProject(requestParameters: CreateProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateResponse> {
        const response = await this.createProjectRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for denyAccessRequest without sending the request
     */
    async denyAccessRequestRequestOpts(requestParameters: DenyAccessRequestRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling denyAccessRequest().'
            );
        }

        if (requestParameters['accessRequestId'] == null) {
            throw new runtime.RequiredError(
                'accessRequestId',
                'Required parameter "accessRequestId" was null or undefined when calling denyAccessRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects/{projectId}/access-requests/{accessRequestId}:deny`;
        urlPath = urlPath.replace('{projectId}', encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace('{accessRequestId}', encodeURIComponent(String(requestParameters['accessRequestId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Denies an access request for the project
     * Deny access request
     */
    async denyAccessRequestRaw(requestParameters: DenyAccessRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.denyAccessRequestRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Denies an access request for the project
     * Deny access request
     */
    async denyAccessRequest(requestParameters: DenyAccessRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.denyAccessRequestRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getAccessRequests without sending the request
     */
    async getAccessRequestsRequestOpts(requestParameters: GetAccessRequestsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getAccessRequests().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['includeClosed'] != null) {
            queryParameters['includeClosed'] = requestParameters['includeClosed'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects/{projectId}/access-requests`;
        urlPath = urlPath.replace('{projectId}', encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Gets users who have requested access to the project
     * Get access requests
     */
    async getAccessRequestsRaw(requestParameters: GetAccessRequestsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ProjectAccessRequest>>> {
        const requestOptions = await this.getAccessRequestsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProjectAccessRequestFromJSON));
    }

    /**
     * Gets users who have requested access to the project
     * Get access requests
     */
    async getAccessRequests(requestParameters: GetAccessRequestsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ProjectAccessRequest>> {
        const response = await this.getAccessRequestsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getDiscoverableProjects without sending the request
     */
    async getDiscoverableProjectsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects/discover`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve a list of projects that a user can request access to
     * Get discoverable projects
     */
    async getDiscoverableProjectsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Project>>> {
        const requestOptions = await this.getDiscoverableProjectsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProjectFromJSON));
    }

    /**
     * Retrieve a list of projects that a user can request access to
     * Get discoverable projects
     */
    async getDiscoverableProjects(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Project>> {
        const response = await this.getDiscoverableProjectsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getProject without sending the request
     */
    async getProjectRequestOpts(requestParameters: GetProjectRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getProject().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects/{projectId}`;
        urlPath = urlPath.replace('{projectId}', encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get detailed project information
     * Get project
     */
    async getProjectRaw(requestParameters: GetProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectDetail>> {
        const requestOptions = await this.getProjectRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectDetailFromJSON(jsonValue));
    }

    /**
     * Get detailed project information
     * Get project
     */
    async getProject(requestParameters: GetProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectDetail> {
        const response = await this.getProjectRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getProjectCreateOptions without sending the request
     */
    async getProjectCreateOptionsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects/options`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get allowed options for creating a project
     * Get project create options
     */
    async getProjectCreateOptionsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectCreateOptions>> {
        const requestOptions = await this.getProjectCreateOptionsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectCreateOptionsFromJSON(jsonValue));
    }

    /**
     * Get allowed options for creating a project
     * Get project create options
     */
    async getProjectCreateOptions(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectCreateOptions> {
        const response = await this.getProjectCreateOptionsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getProjectUsers without sending the request
     */
    async getProjectUsersRequestOpts(requestParameters: GetProjectUsersRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getProjectUsers().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects/{projectId}/permissions`;
        urlPath = urlPath.replace('{projectId}', encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Gets users who have access to the project
     * Get project permissions
     */
    async getProjectUsersRaw(requestParameters: GetProjectUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ProjectUser>>> {
        const requestOptions = await this.getProjectUsersRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProjectUserFromJSON));
    }

    /**
     * Gets users who have access to the project
     * Get project permissions
     */
    async getProjectUsers(requestParameters: GetProjectUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ProjectUser>> {
        const response = await this.getProjectUsersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getProjects without sending the request
     */
    async getProjectsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve a list of projects
     * Get projects
     */
    async getProjectsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Project>>> {
        const requestOptions = await this.getProjectsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProjectFromJSON));
    }

    /**
     * Retrieve a list of projects
     * Get projects
     */
    async getProjects(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Project>> {
        const response = await this.getProjectsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getQuotas without sending the request
     */
    async getQuotasRequestOpts(requestParameters: GetQuotasRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getQuotas().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects/{projectId}/cloud-quotas`;
        urlPath = urlPath.replace('{projectId}', encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves a list of relevant cloud service quotas for project
     * Get cloud quotas
     */
    async getQuotasRaw(requestParameters: GetQuotasRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CloudQuota>>> {
        const requestOptions = await this.getQuotasRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CloudQuotaFromJSON));
    }

    /**
     * Retrieves a list of relevant cloud service quotas for project
     * Get cloud quotas
     */
    async getQuotas(requestParameters: GetQuotasRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CloudQuota>> {
        const response = await this.getQuotasRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for redeployProject without sending the request
     */
    async redeployProjectRequestOpts(requestParameters: RedeployProjectRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling redeployProject().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects/{projectId}:re-deploy`;
        urlPath = urlPath.replace('{projectId}', encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Redeploys cloud resources for a project
     * Redeploy project
     */
    async redeployProjectRaw(requestParameters: RedeployProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.redeployProjectRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Redeploys cloud resources for a project
     * Redeploy project
     */
    async redeployProject(requestParameters: RedeployProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.redeployProjectRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for requestQuotaIncrease without sending the request
     */
    async requestQuotaIncreaseRequestOpts(requestParameters: RequestQuotaIncreaseRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling requestQuotaIncrease().'
            );
        }

        if (requestParameters['requestQuotaIncreaseCommand'] == null) {
            throw new runtime.RequiredError(
                'requestQuotaIncreaseCommand',
                'Required parameter "requestQuotaIncreaseCommand" was null or undefined when calling requestQuotaIncrease().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects/{projectId}/cloud-quotas`;
        urlPath = urlPath.replace('{projectId}', encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: RequestQuotaIncreaseCommandToJSON(requestParameters['requestQuotaIncreaseCommand']),
        };
    }

    /**
     * Request a service quota increase for a project\'s cloud account
     * Request quota increase
     */
    async requestQuotaIncreaseRaw(requestParameters: RequestQuotaIncreaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestQuotaIncreaseResponse>> {
        const requestOptions = await this.requestQuotaIncreaseRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestQuotaIncreaseResponseFromJSON(jsonValue));
    }

    /**
     * Request a service quota increase for a project\'s cloud account
     * Request quota increase
     */
    async requestQuotaIncrease(requestParameters: RequestQuotaIncreaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestQuotaIncreaseResponse> {
        const response = await this.requestQuotaIncreaseRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for setUserProjectRole without sending the request
     */
    async setUserProjectRoleRequestOpts(requestParameters: SetUserProjectRoleOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling setUserProjectRole().'
            );
        }

        if (requestParameters['setUserProjectRoleRequest'] == null) {
            throw new runtime.RequiredError(
                'setUserProjectRoleRequest',
                'Required parameter "setUserProjectRoleRequest" was null or undefined when calling setUserProjectRole().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects/{projectId}/permissions`;
        urlPath = urlPath.replace('{projectId}', encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SetUserProjectRoleRequestToJSON(requestParameters['setUserProjectRoleRequest']),
        };
    }

    /**
     * Sets a user\'s role within a project
     * Set role
     */
    async setUserProjectRoleRaw(requestParameters: SetUserProjectRoleOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.setUserProjectRoleRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Sets a user\'s role within a project
     * Set role
     */
    async setUserProjectRole(requestParameters: SetUserProjectRoleOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.setUserProjectRoleRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for unarchiveProject without sending the request
     */
    async unarchiveProjectRequestOpts(requestParameters: UnarchiveProjectRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling unarchiveProject().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects/{projectId}:unarchive`;
        urlPath = urlPath.replace('{projectId}', encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Sets the project status to active
     * Unarchive project
     */
    async unarchiveProjectRaw(requestParameters: UnarchiveProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.unarchiveProjectRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Sets the project status to active
     * Unarchive project
     */
    async unarchiveProject(requestParameters: UnarchiveProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.unarchiveProjectRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for updateProject without sending the request
     */
    async updateProjectRequestOpts(requestParameters: UpdateProjectRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling updateProject().'
            );
        }

        if (requestParameters['projectInput'] == null) {
            throw new runtime.RequiredError(
                'projectInput',
                'Required parameter "projectInput" was null or undefined when calling updateProject().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects/{projectId}`;
        urlPath = urlPath.replace('{projectId}', encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ProjectInputToJSON(requestParameters['projectInput']),
        };
    }

    /**
     * Updates a project
     * Update project
     */
    async updateProjectRaw(requestParameters: UpdateProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectDetail>> {
        const requestOptions = await this.updateProjectRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectDetailFromJSON(jsonValue));
    }

    /**
     * Updates a project
     * Update project
     */
    async updateProject(requestParameters: UpdateProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectDetail> {
        const response = await this.updateProjectRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateProjectTags without sending the request
     */
    async updateProjectTagsRequestOpts(requestParameters: UpdateProjectTagsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling updateProjectTags().'
            );
        }

        if (requestParameters['tag'] == null) {
            throw new runtime.RequiredError(
                'tag',
                'Required parameter "tag" was null or undefined when calling updateProjectTags().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects/{projectId}:tags`;
        urlPath = urlPath.replace('{projectId}', encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['tag']!.map(TagToJSON),
        };
    }

    /**
     * Sets tags on a project
     * Set project tags
     */
    async updateProjectTagsRaw(requestParameters: UpdateProjectTagsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.updateProjectTagsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Sets tags on a project
     * Set project tags
     */
    async updateProjectTags(requestParameters: UpdateProjectTagsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateProjectTagsRaw(requestParameters, initOverrides);
    }

}
