/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateResponse,
    CreateResponseFromJSON,
    CreateResponseToJSON,
} from '../models/CreateResponse';
import {
    type Sheet,
    SheetFromJSON,
    SheetToJSON,
} from '../models/Sheet';
import {
    type SheetDataRequest,
    SheetDataRequestFromJSON,
    SheetDataRequestToJSON,
} from '../models/SheetDataRequest';
import {
    type SheetDetail,
    SheetDetailFromJSON,
    SheetDetailToJSON,
} from '../models/SheetDetail';
import {
    type SheetIngestRequest,
    SheetIngestRequestFromJSON,
    SheetIngestRequestToJSON,
} from '../models/SheetIngestRequest';
import {
    type SheetInput,
    SheetInputFromJSON,
    SheetInputToJSON,
} from '../models/SheetInput';
import {
    type SheetJob,
    SheetJobFromJSON,
    SheetJobToJSON,
} from '../models/SheetJob';
import {
    type SheetQueryResponse,
    SheetQueryResponseFromJSON,
    SheetQueryResponseToJSON,
} from '../models/SheetQueryResponse';
import {
    type SheetUpdateResponse,
    SheetUpdateResponseFromJSON,
    SheetUpdateResponseToJSON,
} from '../models/SheetUpdateResponse';
import {
    type SqlSortOrder,
    SqlSortOrderFromJSON,
    SqlSortOrderToJSON,
} from '../models/SqlSortOrder';
import {
    type UpdateRowsRequest,
    UpdateRowsRequestFromJSON,
    UpdateRowsRequestToJSON,
} from '../models/UpdateRowsRequest';

export interface CreateSheetRequest {
    projectId: string;
    sheetInput: SheetInput;
}

export interface DeleteSheetRequest {
    projectId: string;
    sheetId: string;
}

export interface GetJobsRequest {
    projectId: string;
    sheetId: string;
}

export interface GetSheetRequest {
    projectId: string;
    sheetId: string;
}

export interface GetSheetDataRequest {
    projectId: string;
    sheetId: string;
    limit?: number;
    page?: number;
    orderBy?: string | null;
    order?: SqlSortOrder;
}

export interface GetSheetsRequest {
    projectId: string;
}

export interface QuerySheetDataRequest {
    projectId: string;
    sheetId: string;
    sheetDataRequest: SheetDataRequest;
}

export interface RefreshViewRequest {
    projectId: string;
    sheetId: string;
}

export interface TriggerIngestRequest {
    projectId: string;
    sheetId: string;
    sheetIngestRequest: SheetIngestRequest;
}

export interface UpdateSheetRequest {
    projectId: string;
    sheetId: string;
    sheetInput: SheetInput;
    dryRun?: boolean;
}

export interface UpdateSheetDataRequest {
    projectId: string;
    sheetId: string;
    updateRowsRequest: UpdateRowsRequest;
}

/**
 * 
 */
export class SheetsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createSheet without sending the request
     */
    async createSheetRequestOpts(requestParameters: CreateSheetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling createSheet().'
            );
        }

        if (requestParameters['sheetInput'] == null) {
            throw new runtime.RequiredError(
                'sheetInput',
                'Required parameter "sheetInput" was null or undefined when calling createSheet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects/{projectId}/sheets`;
        urlPath = urlPath.replace('{projectId}', encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SheetInputToJSON(requestParameters['sheetInput']),
        };
    }

    /**
     * Creates a sheet (table or view)
     * Create sheet
     */
    async createSheetRaw(requestParameters: CreateSheetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateResponse>> {
        const requestOptions = await this.createSheetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateResponseFromJSON(jsonValue));
    }

    /**
     * Creates a sheet (table or view)
     * Create sheet
     */
    async createSheet(requestParameters: CreateSheetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateResponse> {
        const response = await this.createSheetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteSheet without sending the request
     */
    async deleteSheetRequestOpts(requestParameters: DeleteSheetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling deleteSheet().'
            );
        }

        if (requestParameters['sheetId'] == null) {
            throw new runtime.RequiredError(
                'sheetId',
                'Required parameter "sheetId" was null or undefined when calling deleteSheet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects/{projectId}/sheets/{sheetId}`;
        urlPath = urlPath.replace('{projectId}', encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace('{sheetId}', encodeURIComponent(String(requestParameters['sheetId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Deletes a sheet
     * Delete sheet
     */
    async deleteSheetRaw(requestParameters: DeleteSheetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteSheetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes a sheet
     * Delete sheet
     */
    async deleteSheet(requestParameters: DeleteSheetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteSheetRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getJobs without sending the request
     */
    async getJobsRequestOpts(requestParameters: GetJobsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getJobs().'
            );
        }

        if (requestParameters['sheetId'] == null) {
            throw new runtime.RequiredError(
                'sheetId',
                'Required parameter "sheetId" was null or undefined when calling getJobs().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects/{projectId}/sheets/{sheetId}/jobs`;
        urlPath = urlPath.replace('{projectId}', encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace('{sheetId}', encodeURIComponent(String(requestParameters['sheetId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves jobs for a sheet
     * List jobs
     */
    async getJobsRaw(requestParameters: GetJobsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SheetJob>>> {
        const requestOptions = await this.getJobsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SheetJobFromJSON));
    }

    /**
     * Retrieves jobs for a sheet
     * List jobs
     */
    async getJobs(requestParameters: GetJobsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SheetJob>> {
        const response = await this.getJobsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSheet without sending the request
     */
    async getSheetRequestOpts(requestParameters: GetSheetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getSheet().'
            );
        }

        if (requestParameters['sheetId'] == null) {
            throw new runtime.RequiredError(
                'sheetId',
                'Required parameter "sheetId" was null or undefined when calling getSheet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects/{projectId}/sheets/{sheetId}`;
        urlPath = urlPath.replace('{projectId}', encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace('{sheetId}', encodeURIComponent(String(requestParameters['sheetId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves a sheet
     * Get sheet
     */
    async getSheetRaw(requestParameters: GetSheetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SheetDetail>> {
        const requestOptions = await this.getSheetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SheetDetailFromJSON(jsonValue));
    }

    /**
     * Retrieves a sheet
     * Get sheet
     */
    async getSheet(requestParameters: GetSheetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SheetDetail> {
        const response = await this.getSheetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSheetData without sending the request
     * @deprecated
     */
    async getSheetDataRequestOpts(requestParameters: GetSheetDataRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getSheetData().'
            );
        }

        if (requestParameters['sheetId'] == null) {
            throw new runtime.RequiredError(
                'sheetId',
                'Required parameter "sheetId" was null or undefined when calling getSheetData().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['orderBy'] != null) {
            queryParameters['orderBy'] = requestParameters['orderBy'];
        }

        if (requestParameters['order'] != null) {
            queryParameters['order'] = requestParameters['order'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects/{projectId}/sheets/{sheetId}/data`;
        urlPath = urlPath.replace('{projectId}', encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace('{sheetId}', encodeURIComponent(String(requestParameters['sheetId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns paginated rows from a sheet. The first column is always _row_id, which uniquely identifies each row and is required for row updates via PUT. Defaults page=1, limit=1000, order=ASCENDING.
     * Get sheet data
     * @deprecated
     */
    async getSheetDataRaw(requestParameters: GetSheetDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SheetQueryResponse>> {
        const requestOptions = await this.getSheetDataRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SheetQueryResponseFromJSON(jsonValue));
    }

    /**
     * Returns paginated rows from a sheet. The first column is always _row_id, which uniquely identifies each row and is required for row updates via PUT. Defaults page=1, limit=1000, order=ASCENDING.
     * Get sheet data
     * @deprecated
     */
    async getSheetData(requestParameters: GetSheetDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SheetQueryResponse> {
        const response = await this.getSheetDataRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSheets without sending the request
     */
    async getSheetsRequestOpts(requestParameters: GetSheetsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getSheets().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects/{projectId}/sheets`;
        urlPath = urlPath.replace('{projectId}', encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves sheets for a project
     * List sheets
     */
    async getSheetsRaw(requestParameters: GetSheetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Sheet>>> {
        const requestOptions = await this.getSheetsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SheetFromJSON));
    }

    /**
     * Retrieves sheets for a project
     * List sheets
     */
    async getSheets(requestParameters: GetSheetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Sheet>> {
        const response = await this.getSheetsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for querySheetData without sending the request
     */
    async querySheetDataRequestOpts(requestParameters: QuerySheetDataRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling querySheetData().'
            );
        }

        if (requestParameters['sheetId'] == null) {
            throw new runtime.RequiredError(
                'sheetId',
                'Required parameter "sheetId" was null or undefined when calling querySheetData().'
            );
        }

        if (requestParameters['sheetDataRequest'] == null) {
            throw new runtime.RequiredError(
                'sheetDataRequest',
                'Required parameter "sheetDataRequest" was null or undefined when calling querySheetData().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects/{projectId}/sheets/{sheetId}/data/query`;
        urlPath = urlPath.replace('{projectId}', encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace('{sheetId}', encodeURIComponent(String(requestParameters['sheetId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SheetDataRequestToJSON(requestParameters['sheetDataRequest']),
        };
    }

    /**
     * Returns paginated rows from a sheet. The first column is always _row_id, which uniquely identifies each row and is required for row updates via PUT. This is essentially a GET request disguised as a POST so we can pass in a body.
     * Query sheet data
     */
    async querySheetDataRaw(requestParameters: QuerySheetDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SheetQueryResponse>> {
        const requestOptions = await this.querySheetDataRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SheetQueryResponseFromJSON(jsonValue));
    }

    /**
     * Returns paginated rows from a sheet. The first column is always _row_id, which uniquely identifies each row and is required for row updates via PUT. This is essentially a GET request disguised as a POST so we can pass in a body.
     * Query sheet data
     */
    async querySheetData(requestParameters: QuerySheetDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SheetQueryResponse> {
        const response = await this.querySheetDataRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for refreshView without sending the request
     */
    async refreshViewRequestOpts(requestParameters: RefreshViewRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling refreshView().'
            );
        }

        if (requestParameters['sheetId'] == null) {
            throw new runtime.RequiredError(
                'sheetId',
                'Required parameter "sheetId" was null or undefined when calling refreshView().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects/{projectId}/sheets/{sheetId}:refresh`;
        urlPath = urlPath.replace('{projectId}', encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace('{sheetId}', encodeURIComponent(String(requestParameters['sheetId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Re-materializes a view from its source tables
     * Refresh view
     */
    async refreshViewRaw(requestParameters: RefreshViewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.refreshViewRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Re-materializes a view from its source tables
     * Refresh view
     */
    async refreshView(requestParameters: RefreshViewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.refreshViewRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for triggerIngest without sending the request
     */
    async triggerIngestRequestOpts(requestParameters: TriggerIngestRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling triggerIngest().'
            );
        }

        if (requestParameters['sheetId'] == null) {
            throw new runtime.RequiredError(
                'sheetId',
                'Required parameter "sheetId" was null or undefined when calling triggerIngest().'
            );
        }

        if (requestParameters['sheetIngestRequest'] == null) {
            throw new runtime.RequiredError(
                'sheetIngestRequest',
                'Required parameter "sheetIngestRequest" was null or undefined when calling triggerIngest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects/{projectId}/sheets/{sheetId}/ingest`;
        urlPath = urlPath.replace('{projectId}', encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace('{sheetId}', encodeURIComponent(String(requestParameters['sheetId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SheetIngestRequestToJSON(requestParameters['sheetIngestRequest']),
        };
    }

    /**
     * Triggers an async file ingest into the sheet
     * Trigger ingest
     */
    async triggerIngestRaw(requestParameters: TriggerIngestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.triggerIngestRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Triggers an async file ingest into the sheet
     * Trigger ingest
     */
    async triggerIngest(requestParameters: TriggerIngestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.triggerIngestRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for updateSheet without sending the request
     */
    async updateSheetRequestOpts(requestParameters: UpdateSheetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling updateSheet().'
            );
        }

        if (requestParameters['sheetId'] == null) {
            throw new runtime.RequiredError(
                'sheetId',
                'Required parameter "sheetId" was null or undefined when calling updateSheet().'
            );
        }

        if (requestParameters['sheetInput'] == null) {
            throw new runtime.RequiredError(
                'sheetInput',
                'Required parameter "sheetInput" was null or undefined when calling updateSheet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['dryRun'] != null) {
            queryParameters['dryRun'] = requestParameters['dryRun'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects/{projectId}/sheets/{sheetId}`;
        urlPath = urlPath.replace('{projectId}', encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace('{sheetId}', encodeURIComponent(String(requestParameters['sheetId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SheetInputToJSON(requestParameters['sheetInput']),
        };
    }

    /**
     * Idempotent update: send the full target state. Server validates immutable fields match and applies the diff of mutable fields (rename, columns, view definition). For TABLE dryRun, returns the ALTER statements that would run.
     * Update sheet
     */
    async updateSheetRaw(requestParameters: UpdateSheetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SheetUpdateResponse>> {
        const requestOptions = await this.updateSheetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SheetUpdateResponseFromJSON(jsonValue));
    }

    /**
     * Idempotent update: send the full target state. Server validates immutable fields match and applies the diff of mutable fields (rename, columns, view definition). For TABLE dryRun, returns the ALTER statements that would run.
     * Update sheet
     */
    async updateSheet(requestParameters: UpdateSheetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SheetUpdateResponse> {
        const response = await this.updateSheetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateSheetData without sending the request
     */
    async updateSheetDataRequestOpts(requestParameters: UpdateSheetDataRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling updateSheetData().'
            );
        }

        if (requestParameters['sheetId'] == null) {
            throw new runtime.RequiredError(
                'sheetId',
                'Required parameter "sheetId" was null or undefined when calling updateSheetData().'
            );
        }

        if (requestParameters['updateRowsRequest'] == null) {
            throw new runtime.RequiredError(
                'updateRowsRequest',
                'Required parameter "updateRowsRequest" was null or undefined when calling updateSheetData().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects/{projectId}/sheets/{sheetId}/data`;
        urlPath = urlPath.replace('{projectId}', encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace('{sheetId}', encodeURIComponent(String(requestParameters['sheetId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateRowsRequestToJSON(requestParameters['updateRowsRequest']),
        };
    }

    /**
     * Updates specific rows in a TABLE sheet by _row_id. This is a partial update: only the columns included in each entry are modified, all other columns are left unchanged.
     * Update sheet rows
     */
    async updateSheetDataRaw(requestParameters: UpdateSheetDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.updateSheetDataRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Updates specific rows in a TABLE sheet by _row_id. This is a partial update: only the columns included in each entry are modified, all other columns are left unchanged.
     * Update sheet rows
     */
    async updateSheetData(requestParameters: UpdateSheetDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateSheetDataRaw(requestParameters, initOverrides);
    }

}
