/* tslint:disable */
/* eslint-disable */
/**
 * Cirro Data
 * Cirro Data Platform service API
 *
 * The version of the OpenAPI document: latest
 * Contact: support@cirro.bio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateResponse,
  Sheet,
  SheetDataRequest,
  SheetDetail,
  SheetIngestRequest,
  SheetInput,
  SheetJob,
  SheetQueryResponse,
  SheetUpdateResponse,
  SqlSortOrder,
  UpdateRowsRequest,
} from '../models/index';
import {
    CreateResponseFromJSON,
    CreateResponseToJSON,
    SheetFromJSON,
    SheetToJSON,
    SheetDataRequestFromJSON,
    SheetDataRequestToJSON,
    SheetDetailFromJSON,
    SheetDetailToJSON,
    SheetIngestRequestFromJSON,
    SheetIngestRequestToJSON,
    SheetInputFromJSON,
    SheetInputToJSON,
    SheetJobFromJSON,
    SheetJobToJSON,
    SheetQueryResponseFromJSON,
    SheetQueryResponseToJSON,
    SheetUpdateResponseFromJSON,
    SheetUpdateResponseToJSON,
    SqlSortOrderFromJSON,
    SqlSortOrderToJSON,
    UpdateRowsRequestFromJSON,
    UpdateRowsRequestToJSON,
} from '../models/index';

export interface CreateSheetRequest {
    projectId: string;
    sheetInput: SheetInput;
}

export interface DeleteSheetRequest {
    projectId: string;
    sheetId: string;
}

export interface GetJobsRequest {
    projectId: string;
    sheetId: string;
}

export interface GetSheetRequest {
    projectId: string;
    sheetId: string;
}

export interface GetSheetDataRequest {
    projectId: string;
    sheetId: string;
    limit?: number;
    page?: number;
    orderBy?: string | null;
    order?: SqlSortOrder;
}

export interface GetSheetsRequest {
    projectId: string;
}

export interface QuerySheetDataRequest {
    projectId: string;
    sheetId: string;
    sheetDataRequest: SheetDataRequest;
}

export interface RefreshViewRequest {
    projectId: string;
    sheetId: string;
}

export interface TriggerIngestRequest {
    projectId: string;
    sheetId: string;
    sheetIngestRequest: SheetIngestRequest;
}

export interface UpdateSheetRequest {
    projectId: string;
    sheetId: string;
    sheetInput: SheetInput;
    dryRun?: boolean;
}

export interface UpdateSheetDataRequest {
    projectId: string;
    sheetId: string;
    updateRowsRequest: UpdateRowsRequest;
}

/**
 * 
 */
export class SheetsApi extends runtime.BaseAPI {

    /**
     * Creates a sheet (table or view)
     * Create sheet
     */
    async createSheetRaw(requestParameters: CreateSheetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateResponse>> {
        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling createSheet.');
        }

        if (requestParameters.sheetInput === null || requestParameters.sheetInput === undefined) {
            throw new runtime.RequiredError('sheetInput','Required parameter requestParameters.sheetInput was null or undefined when calling createSheet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/projects/{projectId}/sheets`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SheetInputToJSON(requestParameters.sheetInput),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateResponseFromJSON(jsonValue));
    }

    /**
     * Creates a sheet (table or view)
     * Create sheet
     */
    async createSheet(requestParameters: CreateSheetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateResponse> {
        const response = await this.createSheetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes a sheet
     * Delete sheet
     */
    async deleteSheetRaw(requestParameters: DeleteSheetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling deleteSheet.');
        }

        if (requestParameters.sheetId === null || requestParameters.sheetId === undefined) {
            throw new runtime.RequiredError('sheetId','Required parameter requestParameters.sheetId was null or undefined when calling deleteSheet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/projects/{projectId}/sheets/{sheetId}`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"sheetId"}}`, encodeURIComponent(String(requestParameters.sheetId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes a sheet
     * Delete sheet
     */
    async deleteSheet(requestParameters: DeleteSheetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteSheetRaw(requestParameters, initOverrides);
    }

    /**
     * Retrieves jobs for a sheet
     * List jobs
     */
    async getJobsRaw(requestParameters: GetJobsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SheetJob>>> {
        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling getJobs.');
        }

        if (requestParameters.sheetId === null || requestParameters.sheetId === undefined) {
            throw new runtime.RequiredError('sheetId','Required parameter requestParameters.sheetId was null or undefined when calling getJobs.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/projects/{projectId}/sheets/{sheetId}/jobs`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"sheetId"}}`, encodeURIComponent(String(requestParameters.sheetId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SheetJobFromJSON));
    }

    /**
     * Retrieves jobs for a sheet
     * List jobs
     */
    async getJobs(requestParameters: GetJobsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SheetJob>> {
        const response = await this.getJobsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves a sheet
     * Get sheet
     */
    async getSheetRaw(requestParameters: GetSheetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SheetDetail>> {
        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling getSheet.');
        }

        if (requestParameters.sheetId === null || requestParameters.sheetId === undefined) {
            throw new runtime.RequiredError('sheetId','Required parameter requestParameters.sheetId was null or undefined when calling getSheet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/projects/{projectId}/sheets/{sheetId}`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"sheetId"}}`, encodeURIComponent(String(requestParameters.sheetId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SheetDetailFromJSON(jsonValue));
    }

    /**
     * Retrieves a sheet
     * Get sheet
     */
    async getSheet(requestParameters: GetSheetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SheetDetail> {
        const response = await this.getSheetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns paginated rows from a sheet. The first column is always _row_id, which uniquely identifies each row and is required for row updates via PUT. Defaults page=1, limit=1000, order=ASCENDING.
     * Get sheet data
     */
    async getSheetDataRaw(requestParameters: GetSheetDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SheetQueryResponse>> {
        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling getSheetData.');
        }

        if (requestParameters.sheetId === null || requestParameters.sheetId === undefined) {
            throw new runtime.RequiredError('sheetId','Required parameter requestParameters.sheetId was null or undefined when calling getSheetData.');
        }

        const queryParameters: any = {};

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.orderBy !== undefined) {
            queryParameters['orderBy'] = requestParameters.orderBy;
        }

        if (requestParameters.order !== undefined) {
            queryParameters['order'] = requestParameters.order;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/projects/{projectId}/sheets/{sheetId}/data`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"sheetId"}}`, encodeURIComponent(String(requestParameters.sheetId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SheetQueryResponseFromJSON(jsonValue));
    }

    /**
     * Returns paginated rows from a sheet. The first column is always _row_id, which uniquely identifies each row and is required for row updates via PUT. Defaults page=1, limit=1000, order=ASCENDING.
     * Get sheet data
     */
    async getSheetData(requestParameters: GetSheetDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SheetQueryResponse> {
        const response = await this.getSheetDataRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves sheets for a project
     * List sheets
     */
    async getSheetsRaw(requestParameters: GetSheetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Sheet>>> {
        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling getSheets.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/projects/{projectId}/sheets`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SheetFromJSON));
    }

    /**
     * Retrieves sheets for a project
     * List sheets
     */
    async getSheets(requestParameters: GetSheetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Sheet>> {
        const response = await this.getSheetsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns paginated rows from a sheet. The first column is always _row_id, which uniquely identifies each row and is required for row updates via PUT. This is essentially a GET request disguised as a POST so we can pass in a body.
     * Query sheet data
     */
    async querySheetDataRaw(requestParameters: QuerySheetDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SheetQueryResponse>> {
        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling querySheetData.');
        }

        if (requestParameters.sheetId === null || requestParameters.sheetId === undefined) {
            throw new runtime.RequiredError('sheetId','Required parameter requestParameters.sheetId was null or undefined when calling querySheetData.');
        }

        if (requestParameters.sheetDataRequest === null || requestParameters.sheetDataRequest === undefined) {
            throw new runtime.RequiredError('sheetDataRequest','Required parameter requestParameters.sheetDataRequest was null or undefined when calling querySheetData.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/projects/{projectId}/sheets/{sheetId}/data/query`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"sheetId"}}`, encodeURIComponent(String(requestParameters.sheetId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SheetDataRequestToJSON(requestParameters.sheetDataRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SheetQueryResponseFromJSON(jsonValue));
    }

    /**
     * Returns paginated rows from a sheet. The first column is always _row_id, which uniquely identifies each row and is required for row updates via PUT. This is essentially a GET request disguised as a POST so we can pass in a body.
     * Query sheet data
     */
    async querySheetData(requestParameters: QuerySheetDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SheetQueryResponse> {
        const response = await this.querySheetDataRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Re-materializes a view from its source tables
     * Refresh view
     */
    async refreshViewRaw(requestParameters: RefreshViewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling refreshView.');
        }

        if (requestParameters.sheetId === null || requestParameters.sheetId === undefined) {
            throw new runtime.RequiredError('sheetId','Required parameter requestParameters.sheetId was null or undefined when calling refreshView.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/projects/{projectId}/sheets/{sheetId}:refresh`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"sheetId"}}`, encodeURIComponent(String(requestParameters.sheetId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Re-materializes a view from its source tables
     * Refresh view
     */
    async refreshView(requestParameters: RefreshViewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.refreshViewRaw(requestParameters, initOverrides);
    }

    /**
     * Triggers an async file ingest into the sheet
     * Trigger ingest
     */
    async triggerIngestRaw(requestParameters: TriggerIngestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling triggerIngest.');
        }

        if (requestParameters.sheetId === null || requestParameters.sheetId === undefined) {
            throw new runtime.RequiredError('sheetId','Required parameter requestParameters.sheetId was null or undefined when calling triggerIngest.');
        }

        if (requestParameters.sheetIngestRequest === null || requestParameters.sheetIngestRequest === undefined) {
            throw new runtime.RequiredError('sheetIngestRequest','Required parameter requestParameters.sheetIngestRequest was null or undefined when calling triggerIngest.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/projects/{projectId}/sheets/{sheetId}/ingest`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"sheetId"}}`, encodeURIComponent(String(requestParameters.sheetId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SheetIngestRequestToJSON(requestParameters.sheetIngestRequest),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Triggers an async file ingest into the sheet
     * Trigger ingest
     */
    async triggerIngest(requestParameters: TriggerIngestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.triggerIngestRaw(requestParameters, initOverrides);
    }

    /**
     * Idempotent update: send the full target state. Server validates immutable fields match and applies the diff of mutable fields (rename, columns, view definition). For TABLE dryRun, returns the ALTER statements that would run.
     * Update sheet
     */
    async updateSheetRaw(requestParameters: UpdateSheetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SheetUpdateResponse>> {
        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling updateSheet.');
        }

        if (requestParameters.sheetId === null || requestParameters.sheetId === undefined) {
            throw new runtime.RequiredError('sheetId','Required parameter requestParameters.sheetId was null or undefined when calling updateSheet.');
        }

        if (requestParameters.sheetInput === null || requestParameters.sheetInput === undefined) {
            throw new runtime.RequiredError('sheetInput','Required parameter requestParameters.sheetInput was null or undefined when calling updateSheet.');
        }

        const queryParameters: any = {};

        if (requestParameters.dryRun !== undefined) {
            queryParameters['dryRun'] = requestParameters.dryRun;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/projects/{projectId}/sheets/{sheetId}`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"sheetId"}}`, encodeURIComponent(String(requestParameters.sheetId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SheetInputToJSON(requestParameters.sheetInput),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SheetUpdateResponseFromJSON(jsonValue));
    }

    /**
     * Idempotent update: send the full target state. Server validates immutable fields match and applies the diff of mutable fields (rename, columns, view definition). For TABLE dryRun, returns the ALTER statements that would run.
     * Update sheet
     */
    async updateSheet(requestParameters: UpdateSheetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SheetUpdateResponse> {
        const response = await this.updateSheetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates specific rows in a TABLE sheet by _row_id. This is a partial update: only the columns included in each entry are modified, all other columns are left unchanged.
     * Update sheet rows
     */
    async updateSheetDataRaw(requestParameters: UpdateSheetDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.projectId === null || requestParameters.projectId === undefined) {
            throw new runtime.RequiredError('projectId','Required parameter requestParameters.projectId was null or undefined when calling updateSheetData.');
        }

        if (requestParameters.sheetId === null || requestParameters.sheetId === undefined) {
            throw new runtime.RequiredError('sheetId','Required parameter requestParameters.sheetId was null or undefined when calling updateSheetData.');
        }

        if (requestParameters.updateRowsRequest === null || requestParameters.updateRowsRequest === undefined) {
            throw new runtime.RequiredError('updateRowsRequest','Required parameter requestParameters.updateRowsRequest was null or undefined when calling updateSheetData.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/projects/{projectId}/sheets/{sheetId}/data`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters.projectId))).replace(`{${"sheetId"}}`, encodeURIComponent(String(requestParameters.sheetId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateRowsRequestToJSON(requestParameters.updateRowsRequest),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Updates specific rows in a TABLE sheet by _row_id. This is a partial update: only the columns included in each entry are modified, all other columns are left unchanged.
     * Update sheet rows
     */
    async updateSheetData(requestParameters: UpdateSheetDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateSheetDataRaw(requestParameters, initOverrides);
    }

}
